Repository GetStream/stream-chat-swift, pull requests merged in 2020-02, with the labels that each got.

#87 Add linter to Example/Carthage project
  Example/Carthage/ChatExample.xcodeproj/project.pbxproj
  Example/Carthage/ChatExample/ChatViewStyle+Extensions.swift
  Sources/.swiftlint.yml
  Sources/Core/Client/Client+WebSocket.swift
  Sources/Core/Client/Client.swift
  Sources/Core/Client/Endpoint.swift
  Sources/Core/Client/Uploader.swift
  Sources/Core/Client/WebSocket/WebSocket+Response.swift
  Sources/Core/Extensions/Codable+Extensions.swift
  Sources/Core/Extensions/Rx/Reachability+Rx.swift
  Sources/Core/Extensions/Rx/RxStarscream.swift
  Sources/Core/Extensions/String+Extensions.swift
  Sources/Core/Extensions/Utils/RepeatingTimer.swift
  Sources/Core/Model/Attachment.swift
  Sources/Core/Model/Channel+Events.swift
  Sources/Core/Model/Channel.swift
  Sources/Core/Model/Event.swift
  Sources/Core/Model/Filter.swift
  Sources/Core/Model/Pagination.swift
  Sources/Core/Model/Reaction.swift
  Sources/Core/Model/UsersQuery.swift
  Sources/Core/Notifications/Notifications.swift
  Sources/Core/Presenter/Channel Presenter/ChannelPresenter+Events.swift
  Sources/Core/Presenter/Channel Presenter/ChannelPresenter+Request.swift
  Sources/Core/Presenter/Channel Presenter/ChannelPresenter.swift
  Sources/Core/Presenter/ChannelsPresenter.swift
  Sources/Core/Presenter/ChatItem.swift
  Sources/Database/Realm/Model/Channel.swift
  Sources/Database/Realm/Model/ChannelResponse.swift
  Sources/Database/Realm/Model/Message.swift
  Sources/Database/Realm/RealmDatabase.swift
  Sources/UI/Banners/Banners.swift
  Sources/UI/Channels/ChannelTableViewCell.swift
  Sources/UI/Channels/ChannelsViewController.swift
  Sources/UI/Chat/Cells/MessageTableViewCell.swift
  Sources/UI/Chat/Cells/MessageTextEnrichment.swift
  Sources/UI/Chat/Chat View Controller/ChatViewController+Composer.swift
  Sources/UI/Chat/Chat View Controller/ChatViewController+MessageActions.swift
  Sources/UI/Chat/Chat View Controller/ChatViewController.swift
  Sources/UI/Chat/Composer/AttachmentCollectionViewCell.swift
  Sources/UI/Chat/Composer/ComposerAddFileView.swift
  Sources/UI/Chat/Composer/ComposerView+Images.swift
  Sources/UI/Chat/Composer/ComposerView.swift
  Sources/UI/Chat/Composer/UploaderItem+UIImagePickerController.swift
  Sources/UI/Extensions/DataDetector.swift
  Sources/UI/Extensions/Rx/RxDocumentPickerViewController.swift
  Sources/UI/Extensions/UIKit/Reusable/UITableView+Reusable.swift
  Sources/UI/Extensions/UIKit/TableView.swift
  Sources/UI/Extensions/UIKit/UIColor+Extensions.swift
  Sources/UI/Extensions/UIKit/UIImage/UIImage+Icons.swift
  Sources/UI/Extensions/UIKit/UIView+Extensions.swift
  Sources/UI/Image Gallery/MediaGalleryViewController.swift
  Sources/UI/ViewController+ImagePicker.swift
  Sources/UI/ViewController.swift
  Sources/UI/Views/ReactionsView.swift
  Sources/UI/Web View/WebViewController.swift
Labels: enhancement, meta

#95 Fix pan gestures on composerview affect tableview scroll
  CHANGELOG.md
  Sources/UI/Chat/Chat View Controller/ChatViewController+Composer.swift
  Sources/UI/Chat/Chat View Controller/ChatViewController.swift
  Sources/UI/Extensions/Keyboard.swift
Labels: bug, ui

#96 Add pod version check after Client initialization
  Sources/Core/Client/Client+Request.swift
  Sources/Core/Client/Client.swift
Labels: core, enhancement

#97 Fix strikethrough markdown with ~~
  CHANGELOG.md
  Sources/UI/Chat/Cells/MessageTextEnrichment.swift
Labels: bug, ui

#101 Fixed nested frameworks when using Carthage
  CHANGELOG.md
  Example/Carthage/ChatExample.xcodeproj/xcshareddata/xcschemes/ChatExample.xcscheme
  StreamChat.xcodeproj/project.pbxproj
Labels: bug, core
