Repository GetStream/stream-chat-swift, pull requests merged in 2020-05, with the labels that each got.

#233 Add gitattributes file
  .gitattributes
Labels: meta

#234 Suppress local notifications for muted users.
  CHANGELOG.md
  Sources/Core/Notifications/Notifications.swift
Labels: bug, sdk:client

#228 Add Github Actions workflow to rebase release/* branches
  .github/workflows/rebase-release.yml
Labels: enhancement, meta

#232 Fixed ChannelPresenter.uploadManager property access
  CHANGELOG.md
  Sources/Client/URL Session Task/Uploader.swift
  Sources/Core/Presenter/Channel/ChannelPresenter.swift
Labels: bug, sdk:client, sdk:core

#242 Add lane for getting next issue number
  fastlane/Fastfile
  fastlane/README.md
Labels: enhancement, meta

#241 Add ChatViewStyle.avatarViewStyle option
  CHANGELOG.md
  Sources/UI/Chat/Chat View Controller/ChatViewController.swift
  Sources/UI/Style/ChatViewStyle.swift
Labels: enhancement, sdk:ui

#239 Fix image & video uploads from camera
  CHANGELOG.md
  Sources/Core/Presenter/UploadingItem.swift
  Sources/UI/Chat/Chat View Controller/ChatViewController+Composer.swift
  Sources/UI/Chat/Composer/UploaderItem+UIImagePickerController.swift
Labels: bug, enhancement, sdk:ui

#250 CIS-115 Test old iOS SDKs nightly
  .github/workflows/beta.yml
  .github/workflows/ci.yml
  .github/workflows/test-old-ios-versions.yml
  Gemfile
  Gemfile.lock
  StreamChat.xcodeproj/project.pbxproj
  Tests/Client/Unit Tests/ClientLoggerTests.swift
  fastlane/Fastfile
  fastlane/README.md
  fastlane/Scanfile
Labels: enhancement, meta

#255 Remove Podfile.lock from Cocoapods example
  Example/Cocoapods/Podfile.lock
Labels: bug, meta

#247 Add unread message count in query channels response
  CHANGELOG.md
  Sources/Client/Client/Client+Events.swift
  Sources/Client/Client/Client+UnreadCount.swift
  Sources/Client/Model/Channel/Channel+UnreadCount.swift
  Sources/Client/Model/Channel/ChannelResponse.swift
  Sources/Client/Model/Event.swift
  Sources/Client/Model/Message/MessageRead.swift
  Sources/Client/Model/User/User.swift
Labels: enhancement, sdk:client

#256 Fix RxSwift warning
  CHANGELOG.md
  Sources/Core/Client/AutoCancellingSubscription.swift
Labels: bug, sdk:core

#263 [CIS-104] Add log level to log outputs
  CHANGELOG.md
  Example/Sources/AppDelegate.swift
  Sources/Client/Client/Client+Request.swift
  Sources/Client/Client/Client+Setup.swift
  Sources/Client/Client/Client.swift
  Sources/Client/Client/ClientLogger.swift
  Sources/Client/Model/Channel/Channel.swift
  Sources/Client/Model/User/User.swift
  Sources/Client/URL Session Task/ClientURLSessionTaskDelegate.swift
  Sources/Client/Utils/InternetConnection.swift
  Sources/UI/Chat/Chat View Controller/ChatViewController+Composer.swift
  Tests/Client/Integration Tests/TestCase.swift
  Tests/Client/Unit Tests/ClientLoggerTests.swift
Labels: enhancement, sdk:core

#264 [CIS-143] Add isSilent property to messages
  CHANGELOG.md
  SharedClient.swift
  Sources/Client/Client/Client+UnreadCount.swift
  Sources/Client/Model/Channel/Channel+UnreadCount.swift
  Sources/Client/Model/Channel/ChannelResponse.swift
  Sources/Client/Model/Message/Message.swift
  StreamChat.xcodeproj/project.pbxproj
  Tests/Client/Unit Tests/Channel_SilentMessageTests.swift
  Tests/Client/Unit Tests/ClientLoggerTests.swift
  Tests/Client/Unit Tests/Client_SilentMessageTests.swift
Labels: enhancement, sdk:core

#269 Fix clientId is required for queries
  CHANGELOG.md
  Sources/Client/Client/Client.swift
  Sources/Client/Client/Endpoint.swift
Labels: bug, sdk:core

#277 Fix URLSession headers not being assigned
  Sources/Client/Client/Client+Request.swift
Labels: bug, sdk:client

#275 Fix deprecated logger overrides logic
  CHANGELOG.md
  Sources/Client/Client/ClientLogger.swift
Labels: bug, sdk:client

#273 Fix infinite loop when `URLSessionWebSocketTask` fails
  CHANGELOG.md
  Sources/Client/WebSocket/Provider/URLSessionWebSocketProvider.swift
Labels: bug, high, sdk:client

#285 Add contains filter
  CHANGELOG.md
  Sources/Client/Model/Channel/ChannelsQuery.swift
  Sources/Client/Model/Filter.swift
  Sources/Client/Model/SearchQuery.swift
  Tests/Client/Unit Tests/FilterTests.swift
Labels: enhancement, sdk:client

#283 [CIS-117] Add pre-commit hook
  .swiftformat
  bootstrap.sh
  hooks/pre-commit.sh
Labels: enhancement, meta

#288 Add pagination options to queryUsers
  CHANGELOG.md
  Sources/Client/Client/Client+User.swift
  Sources/Client/Model/Pagination.swift
  Sources/Client/Model/User/UsersQuery.swift
  Sources/Core/Client/Client+RxUser.swift
  Tests/Client/Unit Tests/QueryEncodingTests.swift
Labels: enhancement, sdk:client
