Repository GetStream/stream-chat-swift, pull requests merged in 2020-12, with the labels that each got.

#615 [CIS-495] `UIConfig` clean-up
  Sources_v3/StreamChatUI/UIConfig.swift
Labels: v3 ui

#619 Replace UIInputAccessoryView with UIInputAccessoryViewController
  Sources_v3/StreamChatUI/ChatChannel/ChatChannelMessageComposerView.swift
  Sources_v3/StreamChatUI/ChatChannel/ChatChannelVC.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposerInputAccessoryViewController.swift
  StreamChat_v3.xcodeproj/project.pbxproj
Labels: v3 ui

#625 Improve view life cycle methods
  Sources_v3/StreamChatUI/Common Views/BaseViews.swift
Labels: v3 ui

#623 [CIS-481] Logic -> `MessageComposerInputAccessoryViewController`
  Sources_v3/StreamChatUI/ChatChannel/ChatChannelMessageComposerView.swift
  Sources_v3/StreamChatUI/ChatChannel/ChatChannelMessageInputView.swift
  Sources_v3/StreamChatUI/ChatChannel/ChatChannelVC.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposerAttachmentsView.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposerInputAccessoryViewController.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposerSuggestionsViewController.swift
Labels: v3 ui

#626 [CIS-502] Prevent user from overscrolling out of visible content
  Sources_v3/StreamChatUI/ChatChannel/ChatChannelCollectionViewLayout.swift
  Sources_v3/StreamChatUI/ChatChannel/ChatChannelVC.swift
  Sources_v3/StreamChatUI/UIConfig.swift
Labels: v3 ui

#597 Don't adjust composer when keyboard is floating
  CHANGELOG.md
  Sources/UI/Chat/Chat View Controller/ChatViewController+Composer.swift
  Sources/UI/Extensions/Keyboard.swift
Labels: bug, sdk:ui

#633 Introduce color palette into UIConfig
  Sources_v3/StreamChatUI/ChatChannel/ChatChannelMessageComposerView.swift
  Sources_v3/StreamChatUI/ChatChannel/ChatChannelVC.swift
  Sources_v3/StreamChatUI/ChatChannel/ChatMessageBubbleView.swift
  Sources_v3/StreamChatUI/ChatChannel/ChatMessageImageGallery.swift
  Sources_v3/StreamChatUI/ChatChannel/ChatMessageMetadataView.swift
  Sources_v3/StreamChatUI/ChatChannel/ChatMessageReactionsView.swift
  Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListItemView.swift
  Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
  Sources_v3/StreamChatUI/ChatChannelList/ChatReadStatusCheckmarkView.swift
  Sources_v3/StreamChatUI/MessageActionsPopup/ChatMessagePopupViewController.swift
  Sources_v3/StreamChatUI/MessageActionsPopup/MessageActionsView+ActionButton.swift
  Sources_v3/StreamChatUI/MessageActionsPopup/MessageActionsView.swift
  Sources_v3/StreamChatUI/UIConfig.swift
  Sources_v3/StreamChatUI/Utils/UIColor+Extensions.swift
Labels: v3 ui

#636 [CIS-480] Add placeholder to `ChatChannelMessageInputTextView`
  Sources_v3/StreamChatUI/ChatChannel/ChatChannelMessageInputTextView.swift
  Sources_v3/StreamChatUI/ChatChannel/ChatChannelMessageInputView.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposerInputAccessoryViewController.swift
  Sources_v3/StreamChatUI/Generated/L10n.swift
  Sources_v3/StreamChatUI/Resources/en.lproj/Localizable.strings
  Sources_v3/StreamChatUI/UIConfig.swift
  StreamChat_v3.xcodeproj/project.pbxproj
Labels: v3 ui

#638 Add option to disable scroll to bottom when new messages are received
  CHANGELOG.md
  Sources/UI/Chat/Chat View Controller/ChatViewController.swift
Labels: feature

#631 [CIS-473] SuggestionViewController UI
  Sources_v3/StreamChatUI/ChatChannel/MessageComposerCommandCollectionViewCell.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposerInputAccessoryViewController.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposerMentionCollectionViewCell.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposerSuggestionsCollectionView.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposerSuggestionsCollectionViewLayout.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposerSuggestionsViewController.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageInputSlashCommandView.swift
  Sources_v3/StreamChatUI/Resources/Assets.xcassets/Suggestions Icons/Contents.json
  Sources_v3/StreamChatUI/Resources/Assets.xcassets/Suggestions Icons/command_ban.imageset/Contents.json
  Sources_v3/StreamChatUI/Resources/Assets.xcassets/Suggestions Icons/command_ban.imageset/command_ban.pdf
  Sources_v3/StreamChatUI/Resources/Assets.xcassets/Suggestions Icons/command_fallback.imageset/Contents.json
  Sources_v3/StreamChatUI/Resources/Assets.xcassets/Suggestions Icons/command_fallback.imageset/command_fallback.pdf
  Sources_v3/StreamChatUI/Resources/Assets.xcassets/Suggestions Icons/command_flag.imageset/Contents.json
  Sources_v3/StreamChatUI/Resources/Assets.xcassets/Suggestions Icons/command_flag.imageset/command_flag.pdf
  Sources_v3/StreamChatUI/Resources/Assets.xcassets/Suggestions Icons/command_giphy.imageset/Contents.json
  Sources_v3/StreamChatUI/Resources/Assets.xcassets/Suggestions Icons/command_giphy.imageset/command_giphy.pdf
  Sources_v3/StreamChatUI/Resources/Assets.xcassets/Suggestions Icons/command_imgur.imageset/Contents.json
  Sources_v3/StreamChatUI/Resources/Assets.xcassets/Suggestions Icons/command_imgur.imageset/command_imgur.pdf
  Sources_v3/StreamChatUI/Resources/Assets.xcassets/Suggestions Icons/command_mention.imageset/Contents.json
  Sources_v3/StreamChatUI/Resources/Assets.xcassets/Suggestions Icons/command_mention.imageset/command_mention.pdf
  Sources_v3/StreamChatUI/Resources/Assets.xcassets/Suggestions Icons/command_mute.imageset/Contents.json
  Sources_v3/StreamChatUI/Resources/Assets.xcassets/Suggestions Icons/command_mute.imageset/command_mute.pdf
  Sources_v3/StreamChatUI/Resources/Assets.xcassets/Suggestions Icons/command_unban.imageset/Contents.json
  Sources_v3/StreamChatUI/Resources/Assets.xcassets/Suggestions Icons/command_unban.imageset/command_unban.pdf
  Sources_v3/StreamChatUI/Resources/Assets.xcassets/Suggestions Icons/command_unmute.imageset/Contents.json
  Sources_v3/StreamChatUI/Resources/Assets.xcassets/Suggestions Icons/command_unmute.imageset/command_unmute.pdf
  Sources_v3/StreamChatUI/UIConfig.swift
  Sources_v3/StreamChatUI/Utils/CALayer+Extensions.swift
  StreamChat_v3.xcodeproj/project.pbxproj
Labels: v3 ui

#647 Add CI v2 workflow and separate v2/v3 CIs
  .github/workflows/ci.yml
  .github/workflows/ci_v2.yml
Labels: meta

#646 Fix markRead requests failing
  Sample_v3/Samples/SimpleChat/SimpleChatViewController.swift
  Sources_v3/StreamChat/APIClient/Endpoints/Endpoint.swift
  Sources_v3/StreamChat/APIClient/RequestEncoder.swift
  Sources_v3/StreamChat/APIClient/RequestEncoder_Tests.swift
Labels: v3

#659 Add path and path ignore params to PR workflows
  .github/workflows/ci.yml
  .github/workflows/ci_v2.yml
Labels: meta

#672 Improve thread arrow aligment with message border
  Sources_v3/StreamChatUI/ChatChannel/ChatMessageBubbleView.swift
  Sources_v3/StreamChatUI/ChatChannel/ChatMessageThreadInfoView.swift
Labels: v3 ui

#671 [CIS-519] Disable all interactions with message textview except links
  Sources_v3/StreamChatUI/ChatChannel/ChatMessageBubbleView.swift
  Sources_v3/StreamChatUI/Common Views/OnlyLinkTappableTextView.swift
  StreamChat_v3.xcodeproj/project.pbxproj
Labels: v3 ui

#677 Fix initialization of DTOs
  Sources_v3/StreamChat/Database/DTOs/ChannelMemberListQueryDTO.swift
  Sources_v3/StreamChat/Database/DTOs/MessageReactionDTO.swift
Labels: v3

#640 [CIS-488] [Demo] Prototype Channel creation screens
  DemoApp/Base.lproj/Main.storyboard
  DemoApp/ChatPresenter.swift
  DemoApp/CreateChatViewController.swift
  DemoApp/CreateGroupViewController.swift
  DemoApp/LoginViewController.swift
  DemoApp/NameGroupViewController.swift
  StreamChat_v3.xcodeproj/project.pbxproj
Labels: v3 ui

#673 V2: disable reactions when connection is down
  CHANGELOG.md
  Sources/UI/Chat/Chat View Controller/ChatViewController+Cells.swift
Labels: bug

#679 [CIS-474] Presenting Suggestions on ChatVC
  Sources_v3/StreamChatUI/ChatChannel/ChatVC.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposerInputAccessoryViewController.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposerSuggestionsViewController.swift
Labels: v3 ui

#682 Fix `Demo` app
  DemoApp/ChatPresenter.swift
Labels: v3 ui

#687 Create groups for components in ChatViewController
  Sources_v3/StreamChatUI/ChatChannel/ChatMessage/ChatMessageBubbleView.swift
  Sources_v3/StreamChatUI/ChatChannel/ChatMessage/ChatMessageCollectionViewCell.swift
  Sources_v3/StreamChatUI/ChatChannel/ChatMessage/ChatMessageContentView.swift
  Sources_v3/StreamChatUI/ChatChannel/ChatMessage/ChatMessageErrorIndicator.swift
  Sources_v3/StreamChatUI/ChatChannel/ChatMessage/ChatMessageGroupPart.swift
  Sources_v3/StreamChatUI/ChatChannel/ChatMessage/ChatMessageMetadataView.swift
  Sources_v3/StreamChatUI/ChatChannel/ChatMessage/ChatMessageReactionsView.swift
  Sources_v3/StreamChatUI/ChatChannel/ChatMessage/ChatMessageThreadInfoView.swift
  Sources_v3/StreamChatUI/ChatChannel/ChatMessage/ChatRepliedMessageContentView.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerAttachmentCellView.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerAttachmentsView.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerCheckmarkControl.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerCommandCollectionViewCell.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerInputContainerView.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerInputSlashCommandView.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerInputTextView.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerMentionCollectionViewCell.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerSendButton.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerSuggestionsCollectionView.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerSuggestionsCollectionViewLayout.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerSuggestionsViewController.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerView.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerViewController.swift
  Sources_v3/StreamChatUI/UIConfig.swift
  StreamChat_v3.xcodeproj/project.pbxproj
Labels: v3 ui

#689 Make file preview layout less dynamic, to prevent layout loop
  DemoApp/ChatPresenter.swift
  Sources_v3/StreamChatUI/ChatChannel/Attachments/ChatFileAttachmentListView+ItemView.swift
  Sources_v3/StreamChatUI/ChatChannel/ChatMessage/ChatMessageContentView.swift
  StreamChat_v3.xcodeproj/xcshareddata/xcschemes/DemoApp.xcscheme
Labels: v3 ui

#692 [CIS-543] Document picker and attachment sending
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerViewController.swift
  Sources_v3/StreamChatUI/Resources/en.lproj/Localizable.strings
  Sources_v3/StreamChatUI/UIConfig.swift
Labels: v3 ui

#693 Fix UserListUpdater flaky test
  Sources_v3/StreamChat/Workers/UserListUpdater_Tests.swift
Labels: v3

#690 [CIS-513] Presenting Suggestion and creating DataSource
  Sources_v3/StreamChatUI/ChatChannel/ChatVC.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerMentionCollectionViewCell.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerSuggestionsCollectionView.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerSuggestionsViewController.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerViewController.swift
  Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListRouter.swift
Labels: v3 ui

#698 Fix flaky userlistupdater test
  Sources_v3/StreamChat/Workers/UserListUpdater_Tests.swift
Labels: v3

#701 V2: prevent crash on inconsistent row deletion in ChatViewController
  CHANGELOG.md
  Sources/UI/Chat/Chat View Controller/ChatViewController.swift
Labels: bug, sdk:ui

#706 [CIS-524] Message actions UX
  Sources_v3/StreamChatUI/ChatChannel/Reactions/ChatMessageReactionsBubbleView+Default.swift
  Sources_v3/StreamChatUI/MessageActionsPopup/ChatMessagePopupViewController.swift
Labels: v3 ui

#708 Polish Chat creation screen
  DemoApp/Base.lproj/Main.storyboard
  DemoApp/CreateChatViewController.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerViewController.swift
Labels: v3 ui

#707 [CIS-465] Add reaction on tapping user mention
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerViewController.swift
  Sources_v3/StreamChatUI/Generated/L10n.swift
Labels: v3 ui

#699 [CIS-485] Swipe to delete
  Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListCollectionViewCell.swift
  Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListItemView.swift
  Sources_v3/StreamChatUI/ChatChannelList/ChatSwipeableListItemView.swift
  Sources_v3/StreamChatUI/UIConfig.swift
  StreamChat_v3.xcodeproj/project.pbxproj
Labels: v3 ui
