Repository GetStream/stream-chat-swift, pull requests merged in 2020-08, with the labels that each got.

#375 [CIS-263] Remove unneeded readEventsEnabled check in Channel.markRead function
  CHANGELOG.md
  Sources/Client/Client/Client+Channel.swift
Labels: bug, sdk:client

#409 Fix failing stress tests
  Sources_v3/Controllers/ChannelController_Tests.swift
  Sources_v3/Controllers/ChannelListController_Tests.swift
Labels: v3

#408 Add login screen to v3 sample
  Sample_v3/AppDelegate.swift
  Sample_v3/Base.lproj/Main.storyboard
  Sample_v3/LoginViewController.swift
  Sample_v3/Samples/SimpleChat/DetailViewController.swift
  Sample_v3/Samples/SimpleChat/MasterViewController.swift
  Sample_v3/Samples/SimpleChat/SimpleChat.storyboard
  StreamChat_v3.xcodeproj/project.pbxproj
Labels: v3

#406 Preparation for 1-1 channel creation
  Sources_v3/Controllers/ChannelController.swift
  Sources_v3/Controllers/ChannelController_Tests.swift
  Sources_v3/Query/ChannelQuery.swift
  Sources_v3/Workers/ChannelUpdater.swift
  Sources_v3/Workers/ChannelUpdater_Mock.swift
  Sources_v3/Workers/ChannelUpdater_Tests.swift
Labels: v3

#399 [CIS-253] Create 1-1 channels
  Sources_v3/Controllers/ChannelController.swift
  Sources_v3/Controllers/ChannelController_Tests.swift
Labels: v3

#429 [CIS-302] Fix Websocket not handling expired token
  CHANGELOG.md
  Sources/Client/Client/Client+WebSocket.swift
  Sources/Client/WebSocket/WebSocket.swift
  Tests/Client/Unit Tests/WebSocket/WebSocketTests.swift
Labels: bug, sdk:client

#440 [CIS-306] Fix date separators not appearing after a new message
  CHANGELOG.md
  Sources/Core/Presenter/Channel/ChannelPresenter+Events.swift
Labels: bug, sdk:ui

#443 [CIS-307] Fix Device object failing to decode due to backend issue
  CHANGELOG.md
  Sources/Client/Model/Device.swift
Labels: backend, bug, sdk:client

#435 [CIS-301] Internet Connection
  .swiftformat
  Sources_v3/.swiftlint.yml
  Sources_v3/ChatClient.swift
  Sources_v3/Utils/Internet Connection/InternetConnection.swift
  Sources_v3/Utils/Internet Connection/InternetConnection_Tests.swift
  Sources_v3/Utils/Internet Connection/Reachability_Vendor.swift
  StreamChat_v3.xcodeproj/project.pbxproj
  codecov.yml
Labels: v3

#450 Change `User` from struct to class
  CHANGELOG.md
  Sample/Sources/CustomChatViewController.swift
  Sample/Sources/LoginViewController.swift
  Sources/Client/Client/Client+Devices.swift
  Sources/Client/Client/Client+User.swift
  Sources/Client/Model/User/User.swift
Labels: !important, bug, sdk:client

#449 Fix `user.unbanned` event cannot be listened for via channel
  CHANGELOG.md
  Sources/Client/Model/EventType.swift
Labels: !important, bug, sdk:client
