Repository GetStream/stream-chat-swift, pull requests merged in 2020-01, with the labels that each got.

#72 Fixes message grouping issue for new messages
  Sources/Core/Presenter/Channel Presenter/ChannelPresenter+EphemeralMessages.swift
  Sources/Core/Presenter/Channel Presenter/ChannelPresenter+Events.swift
  Sources/Core/Presenter/ChannelsPresenter.swift
  Sources/Core/Presenter/ViewChanges.swift
  Sources/UI/Channels/ChannelsViewController.swift
  Sources/UI/Chat/Chat View Controller/ChatViewController.swift
Labels: bug, ui

#76 Create feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: meta

#79 Add codecov badge to README
  README.md
Labels: meta

#80 [Minor]: Typo in Source files Path
  StreamChatRealm.podspec
Labels: bug

#85 Fix allowing uploading files bigger than limit
  CHANGELOG.md
  Sources/Core/Client/Uploader.swift
  Sources/UI/Chat/Chat View Controller/ChatViewController+Composer.swift
  Sources/UI/Chat/Composer/ComposerView+Files.swift
  Sources/UI/Chat/Composer/ComposerView+Images.swift
  Sources/UI/ViewController+ImagePicker.swift
  Sources/UI/ViewController.swift
  StreamChat.xcodeproj/project.pbxproj
Labels: bug, core, ui

#86 Fix video previews crashing on iOS12
  CHANGELOG.md
  Sources/UI/Web View/WebViewController.swift
Labels: bug, ui
