Repository GetStream/stream-chat-swift, pull requests merged in 2020-09, with the labels that each got.

#462 [CIS-315] Re-watch existing channels after the WSConnection is established
  Sources_v3/ChatClient.swift
  Sources_v3/ChatClient_Tests.swift
  Sources_v3/Workers/Background/ChannelWatchStateUpdater.swift
  Sources_v3/Workers/Background/ChannelWatchStateUpdater_Tests.swift
  StreamChat_v3.xcodeproj/project.pbxproj
Labels: v3

#465 Failing `ChannelWatchStateUpdater` test
  Sources_v3/Workers/Background/ChannelWatchStateUpdater_Tests.swift
Labels: v3

#468 [CIS-326] Fix carthage building v3
  CHANGELOG.md
  Sample/Carthage/ChatExample.xcodeproj/xcshareddata/xcschemes/ChatExample.xcscheme
  StreamChat_v3.xcodeproj/xcshareddata/xcschemes/Sample.xcscheme
  StreamChat_v3.xcodeproj/xcshareddata/xcschemes/StreamChatClient.xcscheme
  StreamChat_v3.xcodeproj/xcshareddata/xcschemes/StreamChatClientTests.xcscheme
Labels: !important, bug

#478 [CIS-341] [CIS-342] V3 Sample: allow specifying id in member actions & show alert on login error
  Sample_v3/AppDelegate.swift
  Sample_v3/Extensions/UITableViewController+KeyboardAvoidance.swift
  Sample_v3/Extensions/UIViewController+Alert.swift
  Sample_v3/LoginViewController.swift
  Sample_v3/Samples/SimpleChat/SimpleChatViewController.swift
  StreamChat_v3.xcodeproj/project.pbxproj
Labels: v3

#477 Fixes ChannelController.startUpdating completion called multiple times
  Sources_v3/Controllers/ChannelController/ChannelController.swift
  Sources_v3/Controllers/ChannelController/ChannelController_Tests.swift
  Sources_v3/Controllers/Controller.swift
Labels: v3

#479 [CIS-308] Add ConnectionController
  Sources_v3/Controllers/ConnectionController/ConnectionController+Combine.swift
  Sources_v3/Controllers/ConnectionController/ConnectionController+Combine_Tests.swift
  Sources_v3/Controllers/ConnectionController/ConnectionController+SwiftUI.swift
  Sources_v3/Controllers/ConnectionController/ConnectionController+SwiftUI_Tests.swift
  Sources_v3/Controllers/ConnectionController/ConnectionController.swift
  Sources_v3/Controllers/ConnectionController/ConnectionController_Tests.swift
  Sources_v3/WebSocketClient/Events/ConnectionEvents.swift
  StreamChat_v3.xcodeproj/project.pbxproj
Labels: v3

#480 [CIS-339] V3 Sample: Send keystroke events
  Sample_v3/AppDelegate.swift
  Sample_v3/LoginViewController.swift
  Sample_v3/Samples/SettingsViewController.swift
  Sample_v3/Samples/SimpleChat/SimpleChannelsViewController.swift
  Sample_v3/Samples/SimpleChat/SimpleChatViewController.swift
  Sources_v3/APIClient/Endpoints/ChannelEndpoints.swift
  Sources_v3/APIClient/Endpoints/ChannelEndpoints_Tests.swift
  Sources_v3/Workers/EventSender.swift
  Sources_v3/Workers/EventSender_Tests.swift
Labels: v3

#485 [CIS-343] Implement `ChannelListView` in `SwiftUI` example
  Sample_v3/Samples/SettingsViewController.swift
  Sample_v3/Samples/SwiftUISimpleChat/ChannelListView.swift
  Sample_v3/Samples/SwiftUISimpleChat/ChatView.swift
Labels: v3

#489 [CIS-347] Re-create background workers on `prepareEnvironmentForNewUser`
  Sources_v3/ChatClient.swift
  Sources_v3/ChatClient_Tests.swift
Labels: v3

#492 [CIS-350] Move `entityName` to extension
  Sources_v3/Database/DTOs/ChannelDTO.swift
  Sources_v3/Database/DTOs/ChannelListQueryDTO.swift
  Sources_v3/Database/DTOs/ChannelReadDTO.swift
  Sources_v3/Database/DTOs/CurrentUserDTO.swift
  Sources_v3/Database/DTOs/MemberModelDTO.swift
  Sources_v3/Database/DTOs/MessageDTO.swift
  Sources_v3/Database/DTOs/UserDTO.swift
  Sources_v3/Utils/Database/NSManagedObject+Extensions.swift
  Sources_v3/Utils/Database/NSManagedObject_Tests.swift
  StreamChat_v3.xcodeproj/project.pbxproj
Labels: v3

#491 Sample v3: fix settings screen crash
  Sample_v3/Samples/CombineSimpleChat/CombineSimpleChannelsViewController.swift
  Sample_v3/Samples/SettingsViewController.swift
  Sample_v3/Samples/SwiftUISimpleChat/ChannelListView.swift
Labels: v3

#486 [CIS-343] Improve v3 SwiftUI sample's ChatView
  Sample_v3/Base.lproj/Main.storyboard
  Sample_v3/Extensions/UIColor+ForUsername.swift
  Sample_v3/LoginViewController.swift
  Sample_v3/Samples/SwiftUISimpleChat/ChannelListView.swift
  Sample_v3/Samples/SwiftUISimpleChat/ChatView.swift
Labels: v3

#502 Sample v3: Upgrade SwiftUI sample to iOS 14
  Sample_v3/Extensions/View+AlertTextField.swift
  Sample_v3/LoginViewController.swift
  Sample_v3/Samples/SwiftUISimpleChat/ChannelListView.swift
  Sample_v3/Samples/SwiftUISimpleChat/ChatView.swift
  StreamChat_v3.xcodeproj/project.pbxproj
Labels: v3

#504 [CIS-283] Update README for StreamChat v3
  Documentation/Assets/Low Level SDK.png
  Documentation/Installation.MD
  README.md
Labels: v3

#506 [CIS-211] Database flushing adjustments
  Sources_v3/ChatClient.swift
  Sources_v3/ChatClient_Mock.swift
  Sources_v3/ChatClient_Tests.swift
  Sources_v3/Config/ChatClientConfig.swift
  Sources_v3/Database/DatabaseContainer.swift
  Sources_v3/Database/DatabaseContainer_Mock.swift
  Sources_v3/Database/DatabaseContainer_Tests.swift
Labels: v3

#509 [CIS-361] Fix memberCount and watcherCount for ChatChannel
  Sources_v3/Database/DTOs/ChannelDTO.swift
  Sources_v3/Database/DTOs/ChannelDTO_Tests.swift
  Sources_v3/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
  Sources_v3/Models/ChannelModel.swift
Labels: v3

#499 Fix Channel mute response not parsed correctly
  CHANGELOG.md
  Sources/Client/Model/Channel/MutedChannel.swift
Labels: bug, sdk:client

#515 Fix update warning displayed for 3.x versions
  CHANGELOG.md
  Sources/Client/Client/Client+Request.swift
Labels: bug, sdk:client

#514 Add slowMode client-side implementation
  CHANGELOG.md
  Sources/Client/Client/Client+Channel.swift
  Sources/Client/Client/Endpoint.swift
  Sources/Client/Model/Channel/Channel+Requests.swift
  Sources/Client/Model/Channel/Channel.swift
  Sources/Core/Client/Channel/Channel+RxRequests.swift
  Sources/Core/Client/Client+RxChannel.swift
Labels: feature, sdk:client

#512 [CIS-352] Audit `SwiftUI` sample
  Sample_v3/Extensions/Channel+MembersInfo.swift
  Sample_v3/Samples/SwiftUISimpleChat/ChannelListView.swift
  Sample_v3/Samples/SwiftUISimpleChat/ChatView.swift
Labels: v3

#513 Sample v3: Improve login experience
  Sample_v3/Base.lproj/Main.storyboard
  Sample_v3/LoginViewController.swift
  Sources_v3/Database/DatabaseContainer.swift
  Sources_v3/Database/DatabaseContainer_Mock.swift
  Sources_v3/Database/DatabaseContainer_Tests.swift
Labels: v3

#517 Sample v3: Create README.md
  Sample_v3/README.md
  sample-bootstrap.sh
Labels: v3

#521 [CIS-178] Add queryMembers API
  CHANGELOG.md
  Sources/Client/Client/Client+Channel.swift
  Sources/Client/Client/Endpoint.swift
  Sources/Client/Model/Channel/Channel+Requests.swift
  Sources/Client/Model/Channel/ChannelQuery.swift
  Sources/Client/Model/Channel/ChannelResponse.swift
  Sources/Core/Client/Channel/Channel+RxRequests.swift
  Sources/Core/Client/Client+RxChannel.swift
  sample-bootstrap.sh
Labels: feature, sdk:client

#523 [CIS-359] Change execution order for stress tests
  Tests_v3/StreamChatClientStressTestPlan.xctestplan
Labels: v3
