Repository GetStream/stream-chat-swift, pull requests merged in 2020-11, with the labels that each got.

#581 Sample v3: Ask for channel name when creating channel
  Sample_v3/Samples/CombineSimpleChat/CombineSimpleChannelsViewController.swift
  Sample_v3/Samples/SimpleChat/SimpleChannelsViewController.swift
  Sample_v3/Samples/SwiftUISimpleChat/ChannelListView.swift
Labels: v3

#586 Fix images are not being attached to message
  CHANGELOG.md
  Sources/UI/Chat/Chat View Controller/ChatViewController+Composer.swift
Labels: bug, sdk:ui

#587 [CIS-414] Implement layout helpers
  Sources_v3/StreamChatUI/Utils/UIView+Extensions.swift
Labels: v3 ui

#589 Open `showWebView` function
  CHANGELOG.md
  Sources/UI/Chat/Chat View Controller/ChatViewController+Cells.swift
  Sources/UI/Chat/Chat View Controller/ChatViewController.swift
  Sources/UI/Web View/WebViewController.swift
Labels: feature, sdk:ui

#592 [CIS-415] Introduce and use Nuke for image loading
  Sources_v3/StreamChatUI/Utils/UIImageView+Extensions.swift
  StreamChat_v3.xcodeproj/project.pbxproj
  StreamChat_v3.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: v3 ui

#604 Add online indicator for 1-1 Chat avatars
  Sources_v3/StreamChatUI/ChatChannelList/ChatChannelAvatarView.swift
  Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListItemView.swift
  Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
  Sources_v3/StreamChatUI/Common Views/OnlineIndicatorView.swift
  StreamChat_v3.xcodeproj/project.pbxproj
Labels: v3 ui

#606 Adds Demo app target
  DemoApp/AppDelegate.swift
  DemoApp/Assets.xcassets/AccentColor.colorset/Contents.json
  DemoApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  DemoApp/Assets.xcassets/Contents.json
  DemoApp/Base.lproj/LaunchScreen.storyboard
  DemoApp/Base.lproj/Main.storyboard
  DemoApp/Info.plist
  DemoApp/SceneDelegate.swift
  DemoApp/ViewController.swift
  StreamChat_v3.xcodeproj/project.pbxproj
  hooks/pre-commit.sh
Labels: v3 ui

#607 Fix "typo" in default implementation of lowlevel controller delegates
  Sources_v3/StreamChat/Controllers/ChannelController/ChannelController.swift
  Sources_v3/StreamChat/Controllers/ChannelListController/ChannelListController.swift
  Sources_v3/StreamChat/Controllers/UserListController/UserListController.swift
Labels: v3

#608 Add notificationChannelDeleted event
  CHANGELOG.md
  Sample/Sources/DarkChannelsViewController.swift
  Sources/Client/Model/Event.swift
  Sources/Client/Model/EventType.swift
  Tests/Client/Unit Tests/EventTests.swift
Labels: feature, sdk:client

#609 Fix bootstrap script
  bootstrap.sh
Labels: meta

#605 Delete most of Swiftlint warnings
  Sample_v3/AppDelegate.swift
  Sample_v3/Configuration.swift
  Sample_v3/ConfigurationViewController.swift
  Sample_v3/Extensions/UITableViewController+KeyboardAvoidance.swift
  Sample_v3/Samples/CombineSimpleChat/CombineSimpleChannelMembersViewController.swift
  Sample_v3/Samples/CombineSimpleChat/CombineSimpleChannelsViewController.swift
  Sample_v3/Samples/CombineSimpleChat/CombineSimpleChatViewController.swift
  Sample_v3/Samples/CombineSimpleChat/CombineSimpleUsersViewController.swift
  Sample_v3/Samples/SimpleChat/SimpleChannelMembersViewController.swift
  Sample_v3/Samples/SimpleChat/SimpleChannelsViewController.swift
  Sample_v3/Samples/SimpleChat/SimpleChatViewController.swift
  Sample_v3/Samples/SimpleChat/SimpleUsersViewController.swift
  Sample_v3/Samples/SwiftUISimpleChat/ChannelListView.swift
  Sample_v3/Samples/SwiftUISimpleChat/ChatView.swift
  Sample_v3/SceneDelegate.swift
  Sources/UI/Chat/Composer/ComposerView+Images.swift
  Tests/Client/Custom Assertions/AssertNetworkRequest.swift
  Tests/Client/Integration Tests/TestCase.swift
  Tests/Client/Unit Tests/AtomicTests.swift
  Tests/Client/Unit Tests/Channel+SetupTests.swift
  Tests/Client/Unit Tests/WebSocket/WebSocketEventsMock.swift
  Tests/Client/Unit Tests/WebSocket/WebSocketProviderMock.swift
  Tests_v3/Mock Network/AssertNetworkRequest.swift
Labels: v3
