Repository GetStream/stream-chat-swift, pull requests merged in 2020-10, with the labels that each got.

#525 [CIS-359] Ensure delegates always have expected-queue-id set in tests
  Sources_v3/Controllers/ChannelController/ChannelController_Tests.swift
  Sources_v3/Controllers/ChannelListController/ChannelListController_Tests.swift
  Sources_v3/Controllers/CurrentUserController/CurrentUserController_Tests.swift
  Sources_v3/Controllers/DataController_Tests.swift
  Sources_v3/Controllers/MessageController/MessageController_Tests.swift
  Tests_v3/QueueAwareDelegate.swift
Labels: v3

#543 [CIS-389] Fix Sorting encoding
  Sources_v3/Query/ChannelMemberListQuery_Tests.swift
  Sources_v3/Query/Sorting.swift
  Sources_v3/Query/Sorting_Tests.swift
  Sources_v3/Query/UserListQuery_Tests.swift
  StreamChat_v3.xcodeproj/project.pbxproj
Labels: v3

#545 [CIS-391] Fix compilation error in Sample
  Sample_v3/Samples/SettingsViewController.swift
Labels: v3

#536 Sample v3: Separate login configurations into a new screen + persistence
  Sample_v3/Base.lproj/Main.storyboard
  Sample_v3/Configuration.swift
  Sample_v3/ConfigurationViewController.swift
  Sample_v3/LoginViewController.swift
  StreamChat_v3.xcodeproj/project.pbxproj
Labels: v3

#555 Fix composerView retaining messages
  CHANGELOG.md
  Sources/UI/Chat/Chat View Controller/ChatViewController+Composer.swift
Labels: bug, sdk:ui

#552 [CIS-382] Implement member actions in samples
  Sample_v3/Extensions/Channel+Extensions.swift
  Sample_v3/Samples/CombineSimpleChat/CombineSimpleChatViewController.swift
  Sample_v3/Samples/SimpleChat/SimpleChatViewController.swift
  Sample_v3/Samples/SwiftUISimpleChat/ChatView.swift
  Sources_v3/Models/Channel.swift
Labels: v3

#559 For #550: Fix replies request pagination not encoded correctly
  CHANGELOG.md
  Sources/Client/Client/Endpoint.swift
  Sources/Client/Model/Pagination.swift
Labels: bug, sdk:client

#566 [CIS-359] Fix stress tests, vol.6
  Tests_v3/StreamChatTests/StreamChatStressTestPlan.xctestplan
Labels: v3

#567 Sample v3: Use non-inverted LazyVStack in SwiftUI sample's ChatView
  Sample_v3/Base.lproj/Main.storyboard
  Sample_v3/Samples/SwiftUISimpleChat/ChannelListView.swift
  Sample_v3/Samples/SwiftUISimpleChat/ChatScrollView.swift
  Sample_v3/Samples/SwiftUISimpleChat/ChatView.swift
  StreamChat_v3.xcodeproj/project.pbxproj
Labels: v3

#570 Add basic files for UI SDK
  Sources_v3/StreamChatUI/ChatChannel/ChatChannelCollectionView.swift
  Sources_v3/StreamChatUI/ChatChannel/ChatChannelCollectionViewDataSource.swift
  Sources_v3/StreamChatUI/ChatChannel/ChatChannelCollectionViewDelegate.swift
  Sources_v3/StreamChatUI/ChatChannel/ChatChannelCollectionViewLayout.swift
  Sources_v3/StreamChatUI/ChatChannel/ChatChannelNavigationBar.swift
  Sources_v3/StreamChatUI/ChatChannel/ChatChannelViewController.swift
  Sources_v3/StreamChatUI/ChatChannel/ChatMessageCollectionViewCell.swift
  Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListCollectionView.swift
  Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListCollectionViewCell.swift
  Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListCollectionViewDataSource.swift
  Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListCollectionViewDelegate.swift
  Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListCollectionViewLayout.swift
  Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListNavigationBar.swift
  Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListViewController.swift
  StreamChat_v3.xcodeproj/project.pbxproj
Labels: v3 ui

#571 [CIS-359] Fix stress tests, vol. 7 | Temporarily disable `MessageSender` tests
  Tests_v3/StreamChatTests/StreamChatStressTestPlan.xctestplan
Labels: v3

#574 Fix internal properties that should've been public
  CHANGELOG.md
  Sources/Client/Model/Channel/Channel.swift
  Sources/Client/Model/Channel/ChannelResponse.swift
Labels: bug, sdk:client

#573 Sample v3: Fix crash on SwiftUI empty channels
  Sample_v3/Samples/SwiftUISimpleChat/ChatView.swift
Labels: v3

#572 Fix plus signs in User fields becoming spaces in the set user request
  CHANGELOG.md
  Sources/Client/Client/Client+WebSocket.swift
  Sources_v3/StreamChat/APIClient/RequestEncoder.swift
  Sources_v3/StreamChat/APIClient/RequestEncoder_Tests.swift
Labels: bug

#575 Change the workaround solution for encoding `+` in URLs
  Sources_v3/StreamChat/APIClient/RequestEncoder.swift
  Sources_v3/StreamChat/APIClient/RequestEncoder_Tests.swift
Labels: v3
