Repository GetStream/stream-chat-swift, pull requests merged in 2020-04, with the labels that each got.

#149 Add memberwise inits for extra data structs
  Sources/Client/Model/Channel/ChannelExtraData.swift
  Sources/Client/Model/User/UserExtraData.swift
Labels: bug, core

#156 Fixed SPM support for 2.0
  CHANGELOG.md
  Package.resolved
  Package.swift
  README.md
  Sources/Core/Client/Client+RxRequest.swift
  Sources/Core/Extensions/InternetConnection+Rx.swift
Labels: bug, enhancement, meta

#158 CIS-80 Remove + operator for pagination
  CHANGELOG.md
  Sources/Client/Client/Client+Channel.swift
  Sources/Client/Client/Client+Channels.swift
  Sources/Client/Client/Client+Events.swift
  Sources/Client/Model/Channel/Channel+Requests.swift
  Sources/Client/Model/Channel/ChannelQuery.swift
  Sources/Client/Model/Channel/ChannelsQuery.swift
  Sources/Client/Model/Pagination.swift
  Sources/Client/Model/SearchQuery.swift
  Sources/Core/Client/Channel/Channel+RxEvents.swift
  Sources/Core/Client/Channel/Channel+RxRequests.swift
  Sources/Core/Client/Client+RxChannel.swift
  Sources/Core/Client/Client+RxChannels.swift
  Sources/Core/Client/Client+RxUnreadCount.swift
  Sources/Core/Client/Client+RxWatcherCount.swift
  Sources/Core/Presenter/Channel/ChannelPresenter+Request.swift
  Sources/Core/Presenter/Channel/ChannelPresenter+RxRequests.swift
  Sources/Core/Presenter/Channel/ChannelPresenter.swift
  Sources/Core/Presenter/Channels/ChannelsPresenter+Rx.swift
  Sources/Core/Presenter/Channels/ChannelsPresenter.swift
  Sources/Core/Presenter/Presenter+Rx.swift
  Tests/Client/Integration Tests/ClientTests01+Channels.swift
  Tests/Client/Integration Tests/ClientTests10+ClientLogger.swift
Labels: core, enhancement

#160 CIS-65 Add verbose error for endpoints requiring connection id
  CHANGELOG.md
  Sources/Client/Client/Client+Request.swift
  Sources/Client/Client/Client.swift
  Sources/Client/Client/ClientError.swift
  Sources/Client/Client/Endpoint.swift
Labels: core, enhancement

#163 Fix Podfile.lock for Cocoapods example
  Example/Cocoapods/Podfile.lock
Labels: bug, example

#167 CIS-38 Fix container.encode for Pagination encoding array
  Sources/Client/Model/Pagination.swift
  StreamChat.xcodeproj/project.pbxproj
  Tests/Client/Unit Tests/QueryEncodingTests.swift
Labels: bug, core

#185 Add nightly fastlane firebase build
  .github/workflows/nightly.yml
  .gitignore
  Example/Carthage/ChatExample.xcodeproj/project.pbxproj
  Example/Carthage/ChatExample.xcodeproj/xcshareddata/xcschemes/ChatExample.xcscheme
  Example/Carthage/ChatExample/Info.plist
  Example/Carthage/fastlane/Fastfile
  Example/Cocoapods/ChatExample.xcodeproj/project.pbxproj
  Gemfile
  Gemfile.lock
  StreamChat.xcodeproj/project.pbxproj
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/Matchfile
  fastlane/Pluginfile
  fastlane/README.md
  fastlane/beta_gym_export_options.plist
Labels: enhancement, meta

#189 Fix composerView hiding behind keyboard after sending bg
  CHANGELOG.md
  Sources/UI/Chat/Chat View Controller/ChatViewController.swift
Labels: bug, ui

#187 Add release lane to fastlane
  Example/Carthage/ChatExample.xcodeproj/project.pbxproj
  Example/Carthage/ChatExample/Info.plist
  Sources/Info.plist
  StreamChat.xcodeproj/project.pbxproj
  fastlane/Fastfile
  fastlane/README.md
  fastlane/actions/touch_changelog.rb
Labels: enhancement, meta

#197 Refactor CI/Beta workflows
  .github/workflows/beta.yml
  .github/workflows/ci.yml
  Tests/Client/TestCase.swift
  fastlane/Fastfile
  fastlane/README.md
  fastlane/Scanfile
Labels: enhancement, meta

#200 CIS-94 Add SPM Example project and integration tests
  .github/workflows/beta.yml
  .github/workflows/ci.yml
  Example/SPM/ChatExample.xcodeproj/project.pbxproj
  Example/SPM/ChatExample.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Example/SPM/ChatExample.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Example/SPM/ChatExample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Example/SPM/ChatExample/ChatExample-Bridging-Header.h
  Example/SPM/ChatExample/Info.plist
  fastlane/Fastfile
  fastlane/README.md
  fastlane/Scanfile
Labels: enhancement, meta

#204 Update Dangerfile to not warn for CHANGELOG when meta tag is used
  Dangerfile
Labels: meta

#206 Fix current user's messages are counted towards unread count
  CHANGELOG.md
  Sources/Client/Client/Client+UnreadCount.swift
Labels: bug, sdk:core

#198 CIS-92 Fix Channel Query default option
  CHANGELOG.md
  Sources/Client/Client/Client+Channel.swift
  Sources/Client/Model/Channel/Channel+Requests.swift
  Sources/Core/Client/Client+RxChannel.swift
Labels: bug, sdk:core

#211 Add Stale bot to repo
  .github/stale.yml
Labels: enhancement, meta

#216 Update MessageViewStyle to add messageInsetSpacing and update Message…
  CHANGELOG.md
  Sources/UI/Chat/Cells/MessageTableViewCell.swift
  Sources/UI/Style/MessageViewStyle.swift
Labels: enhancement, sdk:ui

#207 Tweak readme design
  README.md
Labels: meta

#210 Allow customizing ChatViewController used in Threads
  CHANGELOG.md
  Example/Sources/CustomChatViewController.swift
  Sources/UI/Chat/Chat View Controller/ChatViewController+Cells.swift
  Sources/UI/Chat/Chat View Controller/ChatViewController.swift
Labels: sdk:ui

#215 Fix ImagePicker shows errors when no image is picked
  CHANGELOG.md
  Sources/UI/Chat/Chat View Controller/ChatViewController+Composer.swift
  Sources/UI/Extensions/UIKit/ViewController+ImagePicker.swift
Labels: bug, sdk:ui

#222 Refactor release lane with git checks
  fastlane/Fastfile
Labels: enhancement, meta

#227 Fix keyboard disappearing after every message
  CHANGELOG.md
  Sources/UI/Chat/Chat View Controller/ChatViewController+Composer.swift
Labels: bug, sdk:ui
