Repository GetStream/stream-chat-swift, pull requests merged in 2021-01, with the labels that each got.

#714 UX and UI Fixes of the application
  Sources_v3/StreamChatUI/ChatChannel/ChatChannelRouter.swift
  Sources_v3/StreamChatUI/ChatChannel/ChatMessage/ChatMessageMetadataView.swift
  Sources_v3/StreamChatUI/ChatChannelList/ChatChannelAvatarView.swift
  Sources_v3/StreamChatUI/ChatChannelList/ChatSwipeableListItemView.swift
  Sources_v3/StreamChatUI/Common Views/OnlineIndicatorView.swift
  Sources_v3/StreamChatUI/MessageActionsPopup/ChatMessagePopupViewController.swift
  Sources_v3/StreamChatUI/UIConfig.swift
Labels: v3 ui

#715 Enable bouncing on small content message list
  Sources_v3/StreamChatUI/ChatChannel/ChatMessageListVC.swift
Labels: v3 ui

#716 Use reactions from RN
  Sources_v3/StreamChatUI/UIConfig.swift
Labels: v3 ui

#717 [CIS-554] Fix content jumps on message actions pop-up
  Sources_v3/StreamChatUI/MessageActionsPopup/ChatMessagePopupViewController.swift
Labels: v3 ui

#725 [CIS-560] Fix `textView` height update after mention selection
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerViewController.swift
Labels: v3 ui

#726 Fix layout loop in composer command view
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerInputSlashCommandView.swift
Labels: v3 ui

#727 [V3] Fix crash when dismissing ChannelListVC presented modally
  Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListCollectionViewLayout.swift
Labels: bug, v3 ui

#728 Add Slack bot on failed tests
  .github/workflows/ci.yml
  Sources_v3/StreamChat/APIClient/APIClient_Tests.swift
Labels: meta

#735 Fix photo library permission asked unnecessarily
  CHANGELOG.md
  Sources/UI/Extensions/UIKit/ViewController+ImagePicker.swift
Labels: bug, sdk:ui

#734 Fix message replies are unreachable when message is deleted
  CHANGELOG.md
  Sources/UI/Chat/Chat View Controller/ChatViewController+Cells.swift
Labels: bug, sdk:ui

#738 Fix ComposerView layout overlap when multiple types are uploaded
  CHANGELOG.md
  Sources/UI/Chat/Composer/ComposerView.swift
Labels: bug, sdk:ui

#732 [CIS-546] Fix Suggestion presenting and colors
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerCommandCollectionViewCell.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerMentionCollectionViewCell.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerSuggestionsCollectionView.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerSuggestionsCommandsHeaderView.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerSuggestionsViewController.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerViewController.swift
  Sources_v3/StreamChatUI/Generated/L10n.swift
  Sources_v3/StreamChatUI/Resources/en.lproj/Localizable.strings
  Sources_v3/StreamChatUI/UIConfig.swift
  StreamChat_v3.xcodeproj/project.pbxproj
Labels: v3 ui

#733 Fix QueryUsers is used for TCP heatup
  CHANGELOG.md
  Sources/Client/Client/Client.swift
Labels: bug, sdk:client

#741 Remove session metadata from both versions
  Sources/Client/Client/Client+Request.swift
  Sources_v3/StreamChat/ChatClient.swift
  Sources_v3/StreamChat/ChatClient_Tests.swift
Labels: sdk:client, v3

#744 V2: Fix table view not at bottom when last message is large
  CHANGELOG.md
  Sources/UI/Chat/Chat View Controller/ChatViewController.swift
  Sources/UI/Extensions/UIKit/UITableView+Extensions.swift
Labels: bug, sdk:ui

#743 V2: Add channel property to message
  CHANGELOG.md
  Sources/Client/Model/Channel/Channel.swift
  Sources/Client/Model/Message/Message.swift
Labels: feature, sdk:client

#748 [CIS-583] Resolve design issues in chat creation
  DemoApp/Base.lproj/Main.storyboard
  DemoApp/CreateChatViewController.swift
  DemoApp/CreateGroupViewController.swift
Labels: v3 ui

#747 [CIS-581] Introduce StreamTextStyles, fix minor UI issues in ChannelList
  Sources_v3/StreamChatUI/ChatChannel/Attachments/ChatMessageAttachmentInfoView.swift
  Sources_v3/StreamChatUI/ChatChannel/Attachments/ChatMessageGiphyView.swift
  Sources_v3/StreamChatUI/ChatChannel/Attachments/ChatMessageImageGallery.swift
  Sources_v3/StreamChatUI/ChatChannel/Attachments/ChatMessageInteractiveAttachmentView+ActionButton.swift
  Sources_v3/StreamChatUI/ChatChannel/Attachments/ChatMessageInteractiveAttachmentView.swift
  Sources_v3/StreamChatUI/ChatChannel/Attachments/ChatMessageLinkPreviewView.swift
  Sources_v3/StreamChatUI/ChatChannel/ChatMessage/ChatMessageBubbleView.swift
  Sources_v3/StreamChatUI/ChatChannel/ChatMessage/ChatMessageMetadataView.swift
  Sources_v3/StreamChatUI/ChatChannel/ChatMessage/ChatMessageThreadInfoView.swift
  Sources_v3/StreamChatUI/ChatChannel/ChatReplyBubbleView.swift
  Sources_v3/StreamChatUI/ChatChannel/ChatVC.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerCheckmarkControl.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerCommandCollectionViewCell.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerInputSlashCommandView.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerInputTextView.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerMentionCollectionViewCell.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerSuggestionsCommandsHeaderView.swift
  Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerView.swift
  Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListItemView.swift
  Sources_v3/StreamChatUI/ChatChannelList/ChatUnreadCountView.swift
  Sources_v3/StreamChatUI/MessageActionsPopup/MessageActionsView+ActionButton.swift
  Sources_v3/StreamChatUI/UIConfig.swift
Labels: v3 ui

#759 Adjust hook-script for new file structure
  hooks/pre-commit.sh
Labels: v3

#767 Fix cyrillic letter in `ChatAvatarView` type name
  Sources/StreamChatUI/ChatChannelList/ChatChannelAvatarView.swift
  Sources/StreamChatUI/Common Views/ChatAvatarView.swift
  Sources/StreamChatUI/UIConfig.swift
  StreamChat.xcodeproj/project.pbxproj
Labels: sdk:StreamChatUI

#769 [CIS-600] Remove `.medium` weight from `body` font
  Sources/StreamChatUI/UIConfig.swift
  Sources/StreamChatUI/Utils/UIFont+Extensions.swift
Labels: sdk:StreamChatUI

#756 [CIS-599] Introduce `register_new_device` lane
  fastlane/Fastfile
  fastlane/README.md
Labels: sdk:StreamChat

#761 Move code from setupAppearance to defaultAppearance
  Sources/StreamChatUI/ChatChannelList/ChatChannelListItemView.swift
  Sources/StreamChatUI/ChatChannelList/ChatChannelReadStatusCheckmarkView.swift
  Sources/StreamChatUI/ChatChannelList/ChatChannelUnreadCountView.swift
  Sources/StreamChatUI/ChatMessageList/MessageComposer/ChatMessageComposerSuggestionsViewController.swift
  Sources/StreamChatUI/Common Views/ChatAvatarView.swift
  Sources/StreamChatUI/Common Views/CurrentChatUserAvatarView.swift
Labels: sdk:StreamChatUI

#777 Fix command button in composer
  Sources/StreamChatUI/ChatMessageList/MessageComposer/ChatMessageComposerInputContainerView.swift
  Sources/StreamChatUI/ChatMessageList/MessageComposer/ChatMessageInputSlashCommandView.swift
Labels: bug, sdk:StreamChatUI

#779 [CIS-617] Use resource_bundles for StreamChatUI
  Sources/StreamChatUI/Utils/Bundle+Extensions.swift
  StreamChatUI.podspec
Labels: sdk:StreamChatUI

#781 [CIS-616] Update README with more info about 3.x
  README.md
Labels: meta
