Repository GetStream/stream-chat-swift, pull requests merged in 2022-01, with the labels that each got.

#1745 [CIS-1456] Add hard delete messages support
  CHANGELOG.md
  DemoApp/AppConfigViewController/AppConfigViewController.swift
  DemoApp/AppConfigViewController/OptionsSelectorViewController.swift
  DemoApp/AppConfigViewController/SwitchButton.swift
  DemoApp/AppDelegate.swift
  DemoApp/Base.lproj/Main.storyboard
  DemoApp/DemoAppCoordinator.swift
  DemoApp/LoginViewController.swift
  Sources/StreamChat/APIClient/Endpoints/MessageEndpoints.swift
  Sources/StreamChat/APIClient/Endpoints/MessageEndpoints_Tests.swift
  Sources/StreamChat/Controllers/MessageController/MessageController.swift
  Sources/StreamChat/Controllers/MessageController/MessageController_Tests.swift
  Sources/StreamChat/Database/DTOs/MessageDTO.swift
  Sources/StreamChat/Database/DTOs/MessageDTO_Tests.swift
  Sources/StreamChat/Database/DatabaseSession.swift
  Sources/StreamChat/Database/DatabaseSession_Tests.swift
  Sources/StreamChat/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
  Sources/StreamChat/WebSocketClient/Events/EventPayload.swift
  Sources/StreamChat/WebSocketClient/Events/MessageEvents.swift
  Sources/StreamChat/WebSocketClient/Events/MessageEvents_Tests.swift
  Sources/StreamChat/Workers/MessageUpdater.swift
  Sources/StreamChat/Workers/MessageUpdater_Mock.swift
  Sources/StreamChat/Workers/MessageUpdater_Tests.swift
  Sources/StreamChatUI/MessageActionsPopup/ChatMessageActionsVC.swift
  StreamChat.xcodeproj/project.pbxproj
  StreamChatSample/Base.lproj/Main.storyboard
  Tests/StreamChatTests/MockEnpointResponses/Events/Message/MessageDeletedHard.json
Labels: feature

#1752 [CIS-1288] Fix Message List NSInternalInconsistencyException Crash
  CHANGELOG.md
  DemoApp/DemoAppCoordinator.swift
  Sources/StreamChatUI/ChatChannel/ChatChannelVC_Tests.swift
  Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
  Sources/StreamChatUI/ChatThread/ChatThreadVC_Tests.swift
Labels: bug, !important

#1753 [CIS-1489] Fix Image and Video sharing behaviour
  CHANGELOG.md
  Sources/StreamChatUI/Gallery/GalleryVC.swift
Labels: bug

#1769 Fix shields on README
  README.md
Labels: meta

#1768 [CIS-1254] Fix Composer not showing files when >3 files are selected
  CHANGELOG.md
  Package.swift
  Sources/StreamChatUI/CommonViews/Attachments/AttachmentsPreviewVC.swift
  Sources/StreamChatUI/Composer/ComposerVC_Tests.swift
  Sources/StreamChatUI/Composer/__Snapshots__/ComposerVC_Tests/test_attachmentsPreview_withFourAttachments_addedOneAfterThree.default-light.png
  Sources/StreamChatUI/Composer/__Snapshots__/ComposerVC_Tests/test_attachmentsPreview_withFourAttachments_addedOneAfterThree.extraExtraExtraLarge-light.png
  Sources/StreamChatUI/Composer/__Snapshots__/ComposerVC_Tests/test_attachmentsPreview_withFourAttachments_addedOneAfterThree.rightToLeftLayout-default.png
  Sources/StreamChatUI/Composer/__Snapshots__/ComposerVC_Tests/test_attachmentsPreview_withFourAttachments_addedOneAfterThree.small-dark.png
  Sources/StreamChatUI/Composer/__Snapshots__/ComposerVC_Tests/test_attachmentsPreview_withFourAttachments_addedSameTime.default-light.png
  Sources/StreamChatUI/Composer/__Snapshots__/ComposerVC_Tests/test_attachmentsPreview_withFourAttachments_addedSameTime.extraExtraExtraLarge-light.png
  Sources/StreamChatUI/Composer/__Snapshots__/ComposerVC_Tests/test_attachmentsPreview_withFourAttachments_addedSameTime.rightToLeftLayout-default.png
  Sources/StreamChatUI/Composer/__Snapshots__/ComposerVC_Tests/test_attachmentsPreview_withFourAttachments_addedSameTime.small-dark.png
  Sources/StreamChatUI/Composer/__Snapshots__/ComposerVC_Tests/test_attachmentsPreview_withFourAttachments_addedThreeAfterOne.default-light.png
  Sources/StreamChatUI/Composer/__Snapshots__/ComposerVC_Tests/test_attachmentsPreview_withFourAttachments_addedThreeAfterOne.extraExtraExtraLarge-light.png
  Sources/StreamChatUI/Composer/__Snapshots__/ComposerVC_Tests/test_attachmentsPreview_withFourAttachments_addedThreeAfterOne.rightToLeftLayout-default.png
  Sources/StreamChatUI/Composer/__Snapshots__/ComposerVC_Tests/test_attachmentsPreview_withFourAttachments_addedThreeAfterOne.small-dark.png
  Sources/StreamChatUI/Composer/__Snapshots__/ComposerVC_Tests/test_attachmentsPreview_withFourAttachments_addedTwoAfterTwo.default-light.png
  Sources/StreamChatUI/Composer/__Snapshots__/ComposerVC_Tests/test_attachmentsPreview_withFourAttachments_addedTwoAfterTwo.extraExtraExtraLarge-light.png
  Sources/StreamChatUI/Composer/__Snapshots__/ComposerVC_Tests/test_attachmentsPreview_withFourAttachments_addedTwoAfterTwo.rightToLeftLayout-default.png
  Sources/StreamChatUI/Composer/__Snapshots__/ComposerVC_Tests/test_attachmentsPreview_withFourAttachments_addedTwoAfterTwo.small-dark.png
Labels: bug, sdk:StreamChatUI

#1766 [CIS-1525] Crashfix for hanging DispatchWorkItem reference in WebSocketClient
  CHANGELOG.md
  Sources/StreamChat/WebSocketClient/Engine/URLSessionWebSocketEngine.swift
  Sources/StreamChat/WebSocketClient/WebSocketClient.swift
  Sources/StreamChat/WebSocketClient/WebSocketClient_Tests.swift
  Sources/StreamChat/WebSocketClient/WebSocketPingController.swift
  Sources/StreamChat/WebSocketClient/WebSocketPingController_Tests.swift
Labels: sdk:StreamChat
