Repository GetStream/stream-chat-swift, pull requests merged in 2022-07, with the labels that each got.

#2136 Change upload file size limit to 100MB
  CHANGELOG.md
  Sources/StreamChat/APIClient/CDNClient.swift
  Tests/StreamChatTests/APIClient/StreamCDNClient_Tests.swift
Labels: 🐞 Bug

#2142 [CIS-1970] Update Testflight regression build info
  .github/workflows/testflight.yml
  fastlane/Fastfile
  fastlane/Sonarfile
Labels: 🤖 CI/CD

#2155 [CIS-2044] Add hide history option when adding a new member
  CHANGELOG.md
  DemoApp/StreamChat/Components/DemoChatChannelListRouter.swift
  Sources/StreamChat/APIClient/Endpoints/ChannelEndpoints.swift
  Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
  Sources/StreamChat/Workers/ChannelUpdater.swift
  TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/ChannelUpdater_Mock.swift
  Tests/StreamChatTests/APIClient/Endpoints/ChannelEndpoints_Tests.swift
  Tests/StreamChatTests/Workers/ChannelUpdater_Tests.swift
Labels: 🌐 SDK: StreamChat (LLC), ✅ Feature

#2159 [CIS-1882] Support pagination in mock server
  Sources/StreamChat/Query/Pagination.swift
  StreamChatUITestsAppUITests/Pages/ChannelListPage.swift
  StreamChatUITestsAppUITests/Pages/MessageListPage.swift
  StreamChatUITestsAppUITests/Robots/UserRobot+Asserts.swift
  StreamChatUITestsAppUITests/Tests/ChannelList_Tests.swift
  StreamChatUITestsAppUITests/Tests/MessageList_Tests.swift
  TestTools/StreamChatTestMockServer/MockServer/ChannelResponses.swift
  TestTools/StreamChatTestMockServer/MockServer/MockServerAttributes.swift
Labels: 🤖 CI/CD

#2160 [CIS-1909] Fastlane linting
  .github/workflows/smoke-checks.yml
  .rubocop.yml
  Gemfile
  Gemfile.lock
  fastlane/Allurefile
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/README.md
  fastlane/Sonarfile
  fastlane/actions/retrieve_tests.rb
  fastlane/actions/touch_changelog.rb
Labels: 🤖 CI/CD

#2177 [CIS-2052] Fix crash in ListDatabaseObserver.startObserving()
  CHANGELOG.md
  Sources/StreamChat/Controllers/ListDatabaseObserver.swift
Labels: 🐞 Bug, 🌐 SDK: StreamChat (LLC)

#2186 [CIS-2012] Support link previews in Mock Server
  StreamChat.xcodeproj/project.pbxproj
  StreamChatUITestsAppUITests/Pages/MessageListPage.swift
  StreamChatUITestsAppUITests/Robots/UserRobot+Asserts.swift
  StreamChatUITestsAppUITests/Robots/UserRobot.swift
  StreamChatUITestsAppUITests/Tests/Message Delivery Status/MessageDeliveryStatus_Tests.swift
  StreamChatUITestsAppUITests/Tests/MessageList_Tests.swift
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/http_unsplash_link.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/http_youtube_link.json
  TestTools/StreamChatTestMockServer/MockServer/MessageResponses.swift
  TestTools/StreamChatTestMockServer/MockServer/MockServerAttributes.swift
  TestTools/StreamChatTestMockServer/MockServer/WebsocketResponses.swift
Labels: 🤖 CI/CD
