Repository GetStream/stream-chat-swift, pull requests merged in 2023-11, with the labels that each got.

#2846 Improve bounced messages implementation (NNBB)
  CHANGELOG.md
  Sources/StreamChat/APIClient/Endpoints/Payloads/MessageModerationDetailsPayload.swift
  Sources/StreamChat/APIClient/Endpoints/Payloads/MessagePayloads.swift
  Sources/StreamChat/Database/DTOs/ChannelDTO.swift
  Sources/StreamChat/Database/DTOs/MessageDTO.swift
  Sources/StreamChat/Database/DTOs/MessageModerationDetailsDTO.swift
  Sources/StreamChat/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
  Sources/StreamChat/Errors/ClientError.swift
  Sources/StreamChat/Errors/ErrorPayload.swift
  Sources/StreamChat/Models/ChatMessage.swift
  Sources/StreamChat/Models/MessageModerationDetails.swift
  Sources/StreamChat/Repositories/MessageRepository.swift
  Sources/StreamChat/Workers/Background/MessageEditor.swift
  Sources/StreamChat/Workers/ChannelUpdater.swift
  Sources/StreamChat/Workers/MessageUpdater.swift
  Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageContentView.swift
  Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageLayoutOptionsResolver.swift
  Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
  Sources/StreamChatUI/ChatMessageList/SwipeToReplyGestureHandler.swift
  Sources/StreamChatUI/Generated/L10n.swift
  Sources/StreamChatUI/MessageActionsPopup/ChatMessageActionItem.swift
  Sources/StreamChatUI/MessageActionsPopup/ChatMessageActionsVC.swift
  Sources/StreamChatUI/Resources/en.lproj/Localizable.strings
  Sources/StreamChatUI/Utils/ChatMessage+Extensions.swift
  StreamChat.xcodeproj/project.pbxproj
  TestTools/StreamChatTestTools/Extensions/Unique/ChatMessage+Unique.swift
  TestTools/StreamChatTestTools/Fixtures/JSONs/Message.json
  TestTools/StreamChatTestTools/Mocks/Models + Extensions/ChatMessage_Mock.swift
  TestTools/StreamChatTestTools/Mocks/StreamChat/Repositories/MessageRepository_Mock.swift
  TestTools/StreamChatTestTools/TestData/DummyData/MessagePayload.swift
  Tests/StreamChatTests/APIClient/Endpoints/Payloads/MessagePayloads_Tests.swift
  Tests/StreamChatTests/Database/DTOs/ChannelDTO_Tests.swift
  Tests/StreamChatTests/Database/DTOs/MessageDTO_Tests.swift
  Tests/StreamChatTests/Errors/ClientError_Tests.swift
  Tests/StreamChatTests/Models/MessageModerationDetails_Tests.swift
  Tests/StreamChatTests/Workers/Background/MessageEditor_Tests.swift
  Tests/StreamChatTests/Workers/MessageUpdater_Tests.swift
  Tests/StreamChatUITests/ChatMessage_Tests.swift
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/ChatMessage/ChatMessageContentView_Tests.swift
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/ChatMessage/__Snapshots__/ChatMessageContentView_Tests/test_appearance_whenMessageIsBounced.default-light.png
Labels: 🐞 Bug, 🌐 SDK: StreamChat (LLC), 🎨 SDK: StreamChatUI, ✅ Feature, 🟢 QAed

#2865 Fix empty channel list when querying both hidden or shown channels
  CHANGELOG.md
  Sources/StreamChat/Database/DTOs/ChannelDTO.swift
  Tests/StreamChatTests/Controllers/ChannelListController/ChannelListController_Tests.swift
Labels: 🐞 Bug, 🌐 SDK: StreamChat (LLC)

#2859 Background Mapping - HEAD
  DemoApp/DemoAppConfiguration.swift
  Sources/StreamChat/APIClient/APIClient.swift
  Sources/StreamChat/Config/StreamRuntimeCheck.swift
  Sources/StreamChat/Controllers/BackgroundDatabaseObserver.swift
  Sources/StreamChat/Controllers/BackgroundListDatabaseObserver.swift
  Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
  Sources/StreamChat/Controllers/CurrentUserController/CurrentUserController.swift
  Sources/StreamChat/Controllers/EntityDatabaseObserver.swift
  Sources/StreamChat/Controllers/MemberController/MemberController.swift
  Sources/StreamChat/Controllers/MessageController/MessageController.swift
  Sources/StreamChat/Controllers/UserController/UserController.swift
  Sources/StreamChat/Database/DTOs/ChannelDTO.swift
  Sources/StreamChat/Database/DTOs/MessageDTO.swift
  Sources/StreamChat/Database/DTOs/NSManagedObject+Validation.swift
  Sources/StreamChat/Models/Channel.swift
  Sources/StreamChat/Models/ChatMessage.swift
  Sources/StreamChat/Utils/CoreDataLazy.swift
  Sources/StreamChat/Utils/Database/NSManagedObject+Extensions.swift
  StreamChat.xcodeproj/project.pbxproj
  TestTools/StreamChatTestTools/Mocks/StreamChat/Controllers/EntityDatabaseObserverWrapper_Mock.swift
  TestTools/StreamChatTestTools/Mocks/StreamChat/Controllers/EntityDatabaseObserver_Mock.swift
  TestTools/StreamChatTestTools/Mocks/StreamChat/Controllers/ListDatabaseObserver_Mock.swift
  Tests/StreamChatTests/BackgroundListDatabaseObserver_Tests.swift
  Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
  Tests/StreamChatTests/Controllers/ChannelListController/ChannelListController_Tests.swift
  Tests/StreamChatTests/Controllers/CurrentUserController/CurrentUserController_Tests.swift
  Tests/StreamChatTests/Controllers/MemberController/MemberController_Tests.swift
  Tests/StreamChatTests/Controllers/MessageController/MessageController_Tests.swift
  Tests/StreamChatTests/Controllers/SearchControllers/UserController/UserController_Tests.swift
  Tests/StreamChatTests/Database/DTOs/ChannelDTO_Tests.swift
  Tests/StreamChatTests/Database/DTOs/MessageDTO_Tests.swift
  Tests/StreamChatTests/EntityDatabaseObserverWrapper_Tests.swift
  Tests/StreamChatTests/ListDatabaseObserverWrapper_Tests.swift
  Tests/StreamChatTests/Query/Sorting/ListDatabaseObserver+Sorting_Tests.swift
  Tests/StreamChatTests/StreamChatStressTests/CoreDataLazy_StressTests.swift
  Tests/StreamChatTests/WebSocketClient/EventMiddlewares/UserTypingStateUpdaterMiddleware_Tests.swift
Labels: 🟢 QAed

#2860 Mock-Server with support for members-list and custom channel types
  StreamChat.xcodeproj/project.pbxproj
  TestTools/StreamChatTestMockServer/MockServer/ChannelResponses.swift
  TestTools/StreamChatTestMockServer/MockServer/MembersResponse.swift
  TestTools/StreamChatTestMockServer/MockServer/MockServerAttributes.swift
  TestTools/StreamChatTestMockServer/MockServer/StreamMockServer.swift
Labels: 🤖 CI/CD

#2870 Update header in the test file
  TestTools/StreamChatTestMockServer/MockServer/MembersResponse.swift
Labels: 🤖 CI/CD

#2867 Fix not able to mark channel read after clearing history
  CHANGELOG.md
  Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
  Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
Labels: 🐞 Bug, 🌐 SDK: StreamChat (LLC)

#2879 Add support for editing custom attachments
  CHANGELOG.md
  Sources/StreamChat/ChatClient.swift
  Sources/StreamChat/Models/Attachments/AnyAttachmentPayload.swift
  docusaurus/docs/iOS/uikit/guides/working-with-attachments.md
Labels: 🌐 SDK: StreamChat (LLC), 🎨 SDK: StreamChatUI, ✅ Feature

#2892 [Enhancement]Use `.pin` API to allow overrides
  Sources/StreamChatUI/CommonViews/InputTextView/InputTextView.swift
Labels: ✨ Enhancement

#2884 Fix Message List UI not updated when `message.updatedAt` changes
  CHANGELOG.md
  Sources/StreamChat/Workers/MessageUpdater.swift
  Sources/StreamChatUI/ChatMessageList/ChatMessageListView+DiffKit.swift
  Tests/StreamChatTests/Workers/MessageUpdater_Tests.swift
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/ChatMessageListVC_Tests.swift
Labels: 🐞 Bug, 🎨 SDK: StreamChatUI

#2885 Add new `NewMessageErrorEvent` when observing `EventsController`
  CHANGELOG.md
  Sources/StreamChat/ChatClient.swift
  Sources/StreamChat/Repositories/MessageRepository.swift
  Sources/StreamChat/WebSocketClient/Events/MessageEvents.swift
  Sources/StreamChat/Workers/Background/MessageSender.swift
  Sources/StreamChatUI/ChatChannel/ChatChannelVC.swift
  TestTools/StreamChatTestTools/Mocks/StreamChat/Repositories/MessageRepository_Mock.swift
  Tests/StreamChatTests/Repositories/MessageRepository_Tests.swift
  Tests/StreamChatTests/Workers/Background/MessageSender_Tests.swift
Labels: 🌐 SDK: StreamChat (LLC), ✅ Feature

#2894 Add jump to unread interaction
  CHANGELOG.md
  DemoApp/Screens/AppConfigViewController/AppConfigViewController.swift
  Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
  Sources/StreamChatUI/ChatChannel/ChatChannelVC.swift
  Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
  Sources/StreamChatUI/ChatMessageList/JumpToUnreadMessagesButton.swift
  Sources/StreamChatUI/Components.swift
  Sources/StreamChatUI/Utils/Throttler.swift
  Tests/StreamChatTests/StreamChatFlakyTests.xctestplan
  Tests/StreamChatTests/StreamChatTestPlan.xctestplan
  Tests/StreamChatUITests/Mocks/ChatMessageList/ChatMessageListVCDelegate_Mock.swift
  Tests/StreamChatUITests/SnapshotTests/ChatChannel/ChatChannelVC_Tests.swift
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/ChatMessageListVC_Tests.swift
Labels: 🎨 SDK: StreamChatUI, ✅ Feature, 🟢 QAed

#2901 Fix jump to thread reply when opening channel
  Sources/StreamChatUI/ChatChannel/ChatChannelVC.swift
  TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/EventNotificationCenter_Mock.swift
  Tests/StreamChatTests/Workers/Background/MessageSender_Tests.swift
  Tests/StreamChatUITests/Mocks/ChatMessageList/ChatMessageListVC_Mock.swift
  Tests/StreamChatUITests/SnapshotTests/ChatChannel/ChatChannelVC_Tests.swift
Labels: 🐞 Bug

#2902 Fix marking channel read when `isJumpToUnread` is disabled
  CHANGELOG.md
  Sources/StreamChatUI/ChatChannel/ChatChannelVC.swift
  Tests/StreamChatUITests/SnapshotTests/ChatChannel/ChatChannelVC_Tests.swift
Labels: 🐞 Bug, ❗️ High Priority

#2906 [Background Mapping] Fix Mark as unread
  CHANGELOG.md
  Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
  Sources/StreamChat/Repositories/ChannelRepository.swift
  Sources/StreamChat/Workers/ChannelUpdater.swift
  Sources/StreamChatUI/ChatChannel/ChatChannelVC.swift
  TestTools/StreamChatTestTools/Mocks/StreamChat/Repositories/ChannelRepository_Mock.swift
  TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/ChannelUpdater_Mock.swift
  Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
  Tests/StreamChatTests/Models/ChatChannel_Tests.swift
  Tests/StreamChatTests/Repositories/ChannelRepository_Tests.swift
  Tests/StreamChatTests/Workers/ChannelUpdater_Tests.swift
Labels: 🟢 QAed

#2910 [Background Mapping] Ensure new pages are not requested until the current page has been returned
  Sources/StreamChatUI/ChatChannel/ChatChannelVC.swift
  Sources/StreamChatUI/ChatThread/ChatThreadVC.swift
  Sources/StreamChatUI/Utils/ViewPaginationHandling/InvertedScrollViewPaginationHandler.swift
  Sources/StreamChatUI/Utils/ViewPaginationHandling/StatefulScrollViewPaginationHandler.swift
  Sources/StreamChatUI/Utils/ViewPaginationHandling/ViewPaginationHandling.swift
  StreamChat.xcodeproj/project.pbxproj
  Tests/StreamChatUITests/Utils/ViewPaginationHandling/InvertedScrollViewPaginationHandler_Tests.swift
  Tests/StreamChatUITests/Utils/ViewPaginationHandling/ScrollViewPaginationHandler_Tests.swift
  Tests/StreamChatUITests/Utils/ViewPaginationHandling/StatefulScrollViewPaginationHandler_Tests.swift
Labels: 🟢 QAed
