Repository GetStream/stream-chat-swift, pull requests merged in 2023-02, with the labels that each got.

#2474 Replace ChannelListVC with SplashVC on startup
  Examples/MessengerClone/ChatClient.swift
  Examples/MessengerClone/SceneDelegate.swift
  Examples/Shared/SplashViewController.swift
  Examples/SlackClone/AppDelegate.swift
  Examples/SlackClone/ChatClient.swift
  Examples/YouTubeClone/AppDelegate.swift
  Examples/YouTubeClone/ChatClient.swift
  Examples/iMessageClone/AppDelegate.swift
  Examples/iMessageClone/Assets.xcassets/AccentColor.colorset/Contents.json
  Examples/iMessageClone/ChatClient.swift
  StreamChat.xcodeproj/project.pbxproj
Labels: 🏁 Good Starter

#2476 [Fix]Crash on Demo when user creates channel
  DemoApp/Screens/Create Chat/CreateChatViewController.swift
Labels: 🏁 Good Starter

#2486 Add skip push support when sending a message
  CHANGELOG.md
  DemoApp/StreamChat/Components/DemoChatChannelListRouter.swift
  Sources/StreamChat/APIClient/Endpoints/ChannelEndpoints.swift
  Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
  Sources/StreamChat/Controllers/MessageController/MessageController.swift
  Sources/StreamChat/Database/DTOs/MessageDTO.swift
  Sources/StreamChat/Database/DatabaseSession.swift
  Sources/StreamChat/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
  Sources/StreamChat/Models/Attachments/ChatMessageImageAttachment.swift
  Sources/StreamChat/Repositories/MessageRepository.swift
  Sources/StreamChat/Workers/ChannelUpdater.swift
  Sources/StreamChat/Workers/MessageUpdater.swift
  TestTools/StreamChatTestTools/Mocks/Models + Extensions/Attachments/ChatMessageImageAttachment_Mock.swift
  TestTools/StreamChatTestTools/Mocks/StreamChat/Database/DatabaseSession_Mock.swift
  TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/ChannelUpdater_Mock.swift
  TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/MessageUpdater_Mock.swift
  TestTools/StreamChatTestTools/TestData/AnyEndpoint.swift
  Tests/StreamChatTests/APIClient/Endpoints/ChannelEndpoints_Tests.swift
  Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
  Tests/StreamChatTests/Controllers/MessageController/MessageController_Tests.swift
  Tests/StreamChatTests/Database/DTOs/AttachmentDTO_Tests.swift
  Tests/StreamChatTests/Database/DTOs/MessageDTO_Tests.swift
  Tests/StreamChatTests/Database/DTOs/NSManagedObject+Validation_Tests.swift
  Tests/StreamChatTests/Repositories/MessageRepository_Tests.swift
  Tests/StreamChatTests/Workers/Background/MessageSender_Tests.swift
  Tests/StreamChatTests/Workers/ChannelUpdater_Tests.swift
  Tests/StreamChatTests/Workers/MessageUpdater_Tests.swift
Labels: 🌐 SDK: StreamChat (LLC), ✅ Feature, 🟢 QAed

#2481 Do not store messages from extension if app is receiving events
  Sources/StreamChat/APIClient/ChatRemoteNotificationHandler.swift
  Sources/StreamChat/ChatClient.swift
  Sources/StreamChat/Database/DatabaseContainer.swift
  Sources/StreamChat/Repositories/MessageRepository.swift
  Sources/StreamChat/Utils/NotificationExtension+Lifecycle.swift
  Sources/StreamChat/Workers/Background/ConnectionRecoveryHandler.swift
  Sources/StreamChat/Workers/MessageUpdater.swift
  StreamChat.xcodeproj/project.pbxproj
  TestTools/StreamChatTestTools/Mocks/StreamChat/ChatClient_Mock.swift
  TestTools/StreamChatTestTools/Mocks/StreamChat/Repositories/MessageRepository_Mock.swift
  TestTools/StreamChatTestTools/Mocks/StreamChat/WebSocketClient/EventMiddlewares/NotificationExtensionLifecycle_Mock.swift
  Tests/StreamChatTests/APIClient/ChatPushNotificationContent_Tests.swift
  Tests/StreamChatTests/Repositories/MessageRepository_Tests.swift
  Tests/StreamChatTests/Utils/Database/NSManagedObject_Tests.swift
  Tests/StreamChatTests/Utils/NotificationExtensionLifecycle_Tests.swift
  Tests/StreamChatTests/Workers/Background/ConnectionRecoveryHandler_Tests.swift
Labels: 🤞 Ready For QA

#2494 [BW] Bump fastlane actions version
  .github/workflows/cron-checks.yml
  Gemfile.lock
  Githubfile
  Scripts/bootstrap.sh
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: 🤖 CI/CD

#2488 Implement Local Filter processing for ChannelListController
  CHANGELOG.md
  DemoApp/Screens/AppConfigViewController/AppConfigViewController.swift
  Sources/StreamChat/Config/ChatClientConfig.swift
  Sources/StreamChat/Controllers/ChannelListController/ChannelListController.swift
  Sources/StreamChat/Database/DTOs/ChannelDTO.swift
  Sources/StreamChat/Query/ChannelListQuery.swift
  Sources/StreamChat/Query/Filter+ChatChannel.swift
  Sources/StreamChat/Query/Filter.swift
  TestTools/StreamChatTestTools/TestData/DummyData/XCTestCase+Dummy.swift
  Tests/StreamChatTests/Controllers/ChannelListController/ChannelListController_Tests.swift
  Tests/StreamChatTests/Database/DTOs/ChannelDTO_Tests.swift
  Tests/StreamChatTests/Query/ChannelListFilterScope_Tests.swift
  docusaurus/docs/iOS/client/controllers/channels.md
Labels: 🟢 QAed

#2470 Fix messages appearing sooner in Thread pagination + Fix messages disappearing in Message List
  CHANGELOG.md
  Sources/StreamChat/Database/DTOs/MessageDTO.swift
  Sources/StreamChat/Database/DatabaseContainer.swift
  StreamChat.xcodeproj/xcshareddata/xcbaselines/799C9450247D59B1001F1104.xcbaseline/81176819-54E1-4DC3-B039-A3ED462489C1.plist
  StreamChat.xcodeproj/xcshareddata/xcbaselines/799C9450247D59B1001F1104.xcbaseline/Info.plist
  Tests/StreamChatTests/BackgroundListDatabaseObserver_Tests.swift
  Tests/StreamChatTests/Database/DTOs/MessageDTO_Tests.swift
  Tests/StreamChatTests/ListDatabaseObserver_Tests.swift
Labels: 🐞 Bug, 🌐 SDK: StreamChat (LLC)

#2514 Fix "In" Filter only returning results when all values match
  CHANGELOG.md
  Sources/StreamChat/Query/Filter+ChatChannel.swift
  Tests/StreamChatTests/Controllers/ChannelListController/ChannelListController_Tests.swift
Labels: 🐞 Bug

#2507 Feature/restructure headers footers logic in message cell
  CHANGELOG.md
  Sources/StreamChatUI/ChatChannel/ChatChannelVC.swift
  Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageCell.swift
  Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageDecorationView.swift
  Sources/StreamChatUI/ChatMessageList/ChatMessageListDateSeparatorView.swift
  Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
  Sources/StreamChatUI/ChatMessageList/ChatMessageListVCDelegate.swift
  Sources/StreamChatUI/ChatThread/ChatThreadVC.swift
  Sources/StreamChatUI/Utils/Extensions/UIView+Extensions.swift
  StreamChat.xcodeproj/project.pbxproj
  Tests/StreamChatUITests/SnapshotTests/ChatChannel/ChatChannelVC_Tests.swift
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/ChatMessageListVC_Tests.swift
  Tests/StreamChatUITests/SnapshotTests/CommonViews/ChatMessageCell/ChatMessageCell_DecorationTests.swift
  Tests/StreamChatUITests/SnapshotTests/CommonViews/ChatMessageListDateSeparatorView/ChatMessageListDateSeparatorView_Tests.swift
  docusaurus/docs/iOS/uikit/components/message.md
Labels: 🎨 SDK: StreamChatUI, ✅ Feature
