Repository GetStream/stream-chat-swift, pull requests merged in 2024-05, with the labels that each got.

#3166 Allow to pin any message
  .swiftformat
  CHANGELOG.md
  DemoApp/StreamChat/Components/DemoChatMessageActionsVC.swift
  DemoApp/StreamChat/Components/DemoChatMessageContentView.swift
  Sources/StreamChat/APIClient/Endpoints/EndpointPath+OfflineRequest.swift
  Sources/StreamChat/APIClient/Endpoints/EndpointPath.swift
  Sources/StreamChat/APIClient/Endpoints/MessageEndpoints.swift
  Sources/StreamChat/APIClient/Endpoints/Payloads/MessagePayloads.swift
  Sources/StreamChat/Workers/MessageUpdater.swift
  Tests/StreamChatTests/APIClient/Endpoints/EndpointPath_Tests.swift
  Tests/StreamChatTests/APIClient/Endpoints/MessageEndpoints_Tests.swift
  Tests/StreamChatTests/Workers/MessageUpdater_Tests.swift
Labels: 🐞 Bug, 🌐 SDK: StreamChat (LLC)

#3176 Make `ChatMessageContentView.prepareForReuse()` open
  CHANGELOG.md
  Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageContentView.swift
Labels: 🎨 SDK: StreamChatUI, ✅ Feature

#3174 Fix crash in @Cached property value when computeValue was called
  CHANGELOG.md
  Sources/StreamChat/Utils/Cached.swift
  Tests/StreamChatTests/StreamChatStressTests/Cached_StressTests.swift
Labels: 🐞 Bug, 🌐 SDK: StreamChat (LLC)

#3182 Do not retry rate-limited requests
  CHANGELOG.md
  Sources/StreamChat/APIClient/RequestDecoder.swift
  Tests/StreamChatTests/Errors/ClientError_Tests.swift
Labels: 🌐 SDK: StreamChat (LLC)

#3184 Fix triggering user query calls whenever a new user was added in `UserListController`
  CHANGELOG.md
  Sources/StreamChat/ChatClient.swift
  Sources/StreamChat/Controllers/ReactionListController/ReactionListController.swift
  Sources/StreamChat/Workers/Background/NewUserQueryUpdater.swift
  StreamChat.xcodeproj/project.pbxproj
  Tests/StreamChatTests/ChatClient_Tests.swift
  Tests/StreamChatTests/Workers/Background/NewUserQueryUpdater_Tests.swift
Labels: 🐞 Bug, 🌐 SDK: StreamChat (LLC)

#3187 Fix duplicated watching channel calls when reconnecting
  CHANGELOG.md
  Sources/StreamChat/ChatClient.swift
  Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
  Sources/StreamChat/Controllers/ChannelListController/ChannelListController.swift
  Sources/StreamChat/Utils/ThreadSafeWeakCollection.swift
  Tests/StreamChatTests/ChatClient_Tests.swift
  Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
  Tests/StreamChatTests/Controllers/ChannelListController/ChannelListController_Tests.swift
  Tests/StreamChatTests/Utils/ThreadSafeWeakCollection_Tests.swift
Labels: 🐞 Bug, 🌐 SDK: StreamChat (LLC)

#3188 Only sync at most 250 channels at the same time
  CHANGELOG.md
  Sources/StreamChat/Repositories/SyncRepository.swift
Labels: 🐞 Bug, 🌐 SDK: StreamChat (LLC)

#3186 Improve channel list performance by enabling reconfigure cells
  CHANGELOG.md
  Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
Labels: 🎨 SDK: StreamChatUI

#3181 Add fastlane lane to get the frameworks size and update the README
  README.md
  Scripts/SDKSizeExportOptions.plist
  fastlane/Fastfile
Labels: 🤖 CI/CD

#3193 Fix marking channel read after leaving channel view
  CHANGELOG.md
  Sources/StreamChatUI/ChatChannel/ChatChannelVC.swift
  Tests/StreamChatUITests/SnapshotTests/ChatChannel/ChatChannelVC_Tests.swift
Labels: 🐞 Bug, 🎨 SDK: StreamChatUI

#3197 Update release step
  fastlane/Fastfile
Labels: 🤖 CI/CD

#3199 Archive test logs
  .github/workflows/cron-checks.yml
  .github/workflows/smoke-checks.yml
Labels: 🤖 CI/CD

#3201 Increase the function_body_length rule's warning from 120 to 150
  .swiftlint.yml
Labels: 🤖 CI/CD

#3206 Measure SDKs on release
  .github/workflows/start-new-release.yml
  .gitignore
  fastlane/Fastfile
  fastlane/sdk_size_export_options.plist
Labels: 🤖 CI/CD

#3209 Fetch tags for release workflow
  .github/workflows/start-new-release.yml
Labels: 🤖 CI/CD

#3208 Bump Xcode version on cron checks
  .github/workflows/cron-checks.yml
Labels: 🤖 CI/CD

#3212 Update release lane
  .github/workflows/start-new-release.yml
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: 🤖 CI/CD

#3213 Unit-test instability on older Xcode versions
  Sources/StreamChat/Workers/ChannelUpdater.swift
  Tests/StreamChatTests/StateLayer/ChannelList_Tests.swift
  Tests/StreamChatTests/StateLayer/Chat_Tests.swift
  Tests/StreamChatTests/StateLayer/StateLayerDatabaseObserver_Tests.swift
  Tests/StreamChatTests/StateLayer/UserSearch_Tests.swift
  Tests/StreamChatTests/StreamChatFlakyTests.xctestplan
  Tests/StreamChatTests/StreamChatStressTestPlan.xctestplan
  Tests/StreamChatTests/StreamChatTestPlan.xctestplan
Labels: 🤖 CI/CD

#3215 `ChatSuggestionVC` is getting redisplayed and commands shortcut not working
  CHANGELOG.md
  Sources/StreamChatUI/Composer/ComposerVC.swift
  Sources/StreamChatUI/Composer/Suggestions/ChatSuggestionsVC.swift
  Tests/StreamChatUITests/SnapshotTests/Composer/ComposerVC_Tests.swift
  Tests/StreamChatUITests/SnapshotTests/Composer/__Snapshots__/ComposerVC_Tests/test_showCommandSuggestionsView.default-light.png
  Tests/StreamChatUITests/SnapshotTests/Composer/__Snapshots__/ComposerVC_Tests/test_showMentionSuggestionsView.default-light.png
Labels: 🎨 SDK: StreamChatUI, 🟢 QAed

#3218 Bump rexml from 3.2.6 to 3.2.8
  Gemfile.lock
Labels: 🤖 CI/CD

#3221 Update iOS 15.* version for cron checks
  .github/workflows/cron-checks.yml
Labels: 🤖 CI/CD

#3225 [CI] Bump Xcode and iOS versions
  .github/actions/bootstrap/action.yml
  .github/actions/xcode-cache/action.yml
  .github/workflows/cron-checks.yml
  .github/workflows/smoke-checks.yml
  Tests/StreamChatTests/APIClient/Endpoints/Payloads/ChannelListPayload_Tests.swift
  Tests/StreamChatUITests/SnapshotTests/Composer/ComposerVC_Tests.swift
  Tests/StreamChatUITests/SnapshotTests/Composer/__Snapshots__/ComposerVC_Tests/test_showLinkPreview.default-light.png
  Tests/StreamChatUITests/SnapshotTests/Composer/__Snapshots__/ComposerVC_Tests/test_showLinkPreview.extraExtraExtraLarge-light.png
  Tests/StreamChatUITests/SnapshotTests/Composer/__Snapshots__/ComposerVC_Tests/test_showLinkPreview.rightToLeftLayout-default.png
  Tests/StreamChatUITests/SnapshotTests/Composer/__Snapshots__/ComposerVC_Tests/test_showLinkPreview.small-dark.png
  fastlane/Fastfile
Labels: 🤖 CI/CD
