Repository GetStream/stream-chat-swift, pull requests merged in 2024-08, with the labels that each got.

#3350 [CI] Automate the merge of the release branches
  .github/workflows/release-merge.yml
  .github/workflows/release-publish.yml
  .github/workflows/release-start.yml
  fastlane/Fastfile
Labels: 🤖 CI/CD

#3354 [CI] Fix the merge release flow
  .github/workflows/release-merge.yml
  fastlane/Fastfile
Labels: 🤖 CI/CD

#3356 [CI] Enable workflow dispatch for release merge
  .github/workflows/release-merge.yml
Labels: 🤖 CI/CD

#3358 [CI] Sync Mock Server
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/http_add_member.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/http_attachment.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/http_channel_creation.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/http_channel_removal.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/http_channels.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/http_events.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/http_message.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/http_message_ephemeral.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/http_reaction.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/http_truncate.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/http_unsplash_link.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/http_youtube_link.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/ws_events.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/ws_events_channel.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/ws_events_member.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/ws_health_check.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/ws_message.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/ws_reaction.json
Labels: 🤖 CI/CD

#3355 Fix rare crashes when deleting local database content on logout
  CHANGELOG.md
  Sources/StreamChat/Database/DatabaseContainer.swift
  Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
  Tests/StreamChatTests/Database/DatabaseContainer_Tests.swift
Labels: 🐞 Bug, 🌐 SDK: StreamChat (LLC), 🟢 QAed

#3357 Use background database observers for remaining controller properties
  CHANGELOG.md
  Sources/StreamChat/Controllers/CurrentUserController/CurrentUserController.swift
  Sources/StreamChat/Controllers/MemberListController/MemberListController.swift
  Sources/StreamChat/Controllers/MessageController/MessageController.swift
  TestTools/StreamChatTestTools/SpyPattern/QueueAware/UserController_Delegate.swift
  Tests/StreamChatTests/Controllers/CurrentUserController/CurrentUserController_Tests.swift
  Tests/StreamChatTests/Controllers/MemberListController/MemberListController_Tests.swift
  Tests/StreamChatTests/Controllers/MessageController/MessageController_Tests.swift
Labels: 🌐 SDK: StreamChat (LLC), ⚡ Performance, 🟢 QAed

#3362 [CI] Update gems
  Gemfile.lock
Labels: 🤖 CI/CD

#3361 Fix crash in MulticastDelegate caused by concurrent accesses
  CHANGELOG.md
  Sources/StreamChat/Utils/MulticastDelegate.swift
  Tests/StreamChatTests/Utils/MulticastDelegate_Tests.swift
Labels: 🐞 Bug

#3360 Remove obsoleted EntityDatabaseObserver and ListDatabaseObserver
  Sources/StreamChat/Controllers/DatabaseObserver/EntityChange.swift
  Sources/StreamChat/Controllers/DatabaseObserver/EntityDatabaseObserver.swift
  Sources/StreamChat/Controllers/DatabaseObserver/ListChange.swift
  Sources/StreamChat/StateLayer/ChannelListState+Observer.swift
  Sources/StreamChat/StateLayer/ChatState+Observer.swift
  Sources/StreamChat/StateLayer/ConnectedUserState+Observer.swift
  Sources/StreamChat/StateLayer/DatabaseObserver/StateLayerDatabaseObserver.swift
  Sources/StreamChat/StateLayer/MemberListState+Observer.swift
  Sources/StreamChat/StateLayer/MessageSearchState+Observer.swift
  Sources/StreamChat/StateLayer/MessageState+Observer.swift
  Sources/StreamChat/StateLayer/ReactionListState+Observer.swift
  Sources/StreamChat/StateLayer/UserListState+Observer.swift
  Sources/StreamChat/Utils/Cached.swift
  Sources/StreamChat/Workers/Background/AttachmentQueueUploader.swift
  Sources/StreamChat/Workers/Background/MessageEditor.swift
  Sources/StreamChat/Workers/Background/MessageSender.swift
  StreamChat.xcodeproj/project.pbxproj
  TestTools/StreamChatTestTools/Mocks/StreamChat/Controllers/BackgroundListDatabaseObserver_Mock.swift
  TestTools/StreamChatTestTools/Mocks/StreamChat/Controllers/EntityDatabaseObserver_Mock.swift
  TestTools/StreamChatTestTools/Mocks/StreamChat/Controllers/ListDatabaseObserver_Mock.swift
  TestTools/StreamChatTestTools/Mocks/StreamChat/Utils/TestChannelListObserver.swift
  TestTools/StreamChatTestTools/Mocks/StreamChat/Utils/TestChannelObserver.swift
  Tests/StreamChatTests/Database/DTOs/AttachmentDTO_Tests.swift
  Tests/StreamChatTests/Database/DTOs/ChannelReadDTO_Tests.swift
  Tests/StreamChatTests/Database/DTOs/MessageDTO_Tests.swift
  Tests/StreamChatTests/Database/DTOs/UserDTO_Tests.swift
  Tests/StreamChatTests/EntityDatabaseObserverWrapper_Tests.swift
  Tests/StreamChatTests/EntityDatabaseObserver_Tests.swift
  Tests/StreamChatTests/ListDatabaseObserver_Tests.swift
  Tests/StreamChatTests/StateLayer/StateLayerDatabaseObserver_Tests.swift
  Tests/StreamChatTests/StreamChatStressTests/Cached_StressTests.swift
  Tests/StreamChatTests/WebSocketClient/EventMiddlewares/MemberEventMiddleware_Tests.swift
Labels: 🌐 SDK: StreamChat (LLC), 🟢 QAed

#3365 Improve database container read and reset
  Sources/StreamChat/Database/DTOs/CurrentUserDTO.swift
  Sources/StreamChat/Database/DTOs/MessageDTO.swift
  Sources/StreamChat/Database/DatabaseContainer.swift
  Sources/StreamChat/Database/DatabaseSession.swift
  Sources/StreamChat/Repositories/MessageRepository.swift
  Sources/StreamChat/Workers/ChannelUpdater.swift
  TestTools/StreamChatTestTools/Mocks/StreamChat/Database/DatabaseSession_Mock.swift
Labels: 🐞 Bug, 🟢 QAed

#3370 [CI] Rename metrics repo
  fastlane/Fastfile
Labels: 🤖 CI/CD

#3375 [CI] Bump fastlane actions plugin
  Gemfile.lock
  fastlane/Pluginfile
Labels: 🤖 CI/CD

#3376 [CI] Bump fastlane plugin version
  Gemfile.lock
  fastlane/Pluginfile
Labels: 🤖 CI/CD

#3367 Run offline state sync in the background
  CHANGELOG.md
  Sources/StreamChat/ChatClient+Environment.swift
  Sources/StreamChat/ChatClient.swift
  Sources/StreamChat/Config/StreamRuntimeCheck.swift
  Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
  Sources/StreamChat/Controllers/ChannelListController/ChannelListController.swift
  Sources/StreamChat/Repositories/SyncOperations.swift
  Sources/StreamChat/Repositories/SyncRepository.swift
  Sources/StreamChat/StateLayer/ChannelList.swift
  Sources/StreamChat/StateLayer/Chat.swift
  Sources/StreamChat/StateLayer/ChatClient+Factory.swift
  Sources/StreamChat/Workers/ChannelListUpdater.swift
  TestTools/StreamChatTestTools/Mocks/StreamChat/Controllers/ChatChannelListController_Mock.swift
  TestTools/StreamChatTestTools/Mocks/StreamChat/Repositories/SyncRepository_Mock.swift
  TestTools/StreamChatTestTools/SpyPattern/Spy/APIClient_Spy.swift
  TestTools/StreamChatTestTools/TestData/DummyData/XCTestCase+Dummy.swift
  Tests/StreamChatTests/ChatClient_Tests.swift
  Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
  Tests/StreamChatTests/Controllers/ChannelListController/ChannelListController_Tests.swift
  Tests/StreamChatTests/Repositories/SyncOperations_Tests.swift
  Tests/StreamChatTests/Repositories/SyncRepository_Tests.swift
  Tests/StreamChatTests/StateLayer/ChannelList_Tests.swift
Labels: 🌐 SDK: StreamChat (LLC), ✅ Feature, 🟢 QAed

#3372 High CPU usage while typing
  CHANGELOG.md
  Sources/StreamChat/ChatClient.swift
  Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
  TestTools/StreamChatTestTools/Mocks/StreamChat/ChatClient_Mock.swift
  Tests/StreamChatTests/ChatClient_Tests.swift
  Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
Labels: 🌐 SDK: StreamChat (LLC), ⚡ Performance, 🟢 QAed

#3379 [CI] Add space to SDK size badge
  Gemfile.lock
  README.md
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: 🤖 CI/CD

#3373 Fix reading the local database state just after the initial write
  CHANGELOG.md
  Sources/StreamChat/Controllers/DatabaseObserver/BackgroundDatabaseObserver.swift
  Sources/StreamChat/Utils/Database/DatabaseItemConverter.swift
  Tests/StreamChatTests/BackgroundListDatabaseObserver_Tests.swift
  Tests/StreamChatTests/StreamChatFlakyTests.xctestplan
  Tests/StreamChatTests/StreamChatTestPlan.xctestplan
Labels: 🐞 Bug, 🌐 SDK: StreamChat (LLC), 🟢 QAed

#3383 [CI] Set up a default base branch when automatically creating PRs
  Gemfile.lock
  fastlane/Pluginfile
Labels: 🤖 CI/CD

#3378 Store pending message along with regular messages
  CHANGELOG.md
  Sources/StreamChat/APIClient/Endpoints/Payloads/ChannelListPayload.swift
  Sources/StreamChat/Database/DTOs/ChannelDTO.swift
  TestTools/StreamChatTestTools/Fixtures/JSONs/Channel.json
  TestTools/StreamChatTestTools/TestData/DummyData/ChannelPayload.swift
  TestTools/StreamChatTestTools/TestData/DummyData/XCTestCase+Dummy.swift
  Tests/StreamChatTests/APIClient/Endpoints/Payloads/ChannelListPayload_Tests.swift
  Tests/StreamChatTests/APIClient/Endpoints/Payloads/IdentifiablePayload_Tests.swift
  Tests/StreamChatTests/Database/DTOs/ChannelDTO_Tests.swift
  Tests/StreamChatTests/StateLayer/Chat_Tests.swift
  Tests/StreamChatTests/WebSocketClient/EventMiddlewares/ChannelReadUpdaterMiddleware_Tests.swift
Labels: 🌐 SDK: StreamChat (LLC), ✅ Feature, 🟢 QAed

#3385 [CI] Fetch all branches on release
  fastlane/Fastfile
Labels: 🤖 CI/CD

#3386 [CI] Run release action on workflow dispatch
  .github/workflows/release-publish.yml
Labels: 🤖 CI/CD

#3387 4.62.0 Release
  .github/workflows/release-publish.yml
Labels: 🤖 CI/CD

#3390 4.62.0 Release
  .github/workflows/release-publish.yml
Labels: 🤖 CI/CD

#3391 [CI] Share lanes across projects
  .github/workflows/release-merge.yml
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: 🤖 CI/CD

#3392 [CI] Ensure release version is not empty
  fastlane/Fastfile
Labels: 🤖 CI/CD

#3381 [Polls] Add `PollResultsVC`
  CHANGELOG.md
  Sources/StreamChat/APIClient/Endpoints/Payloads/PollsPayloads.swift
  Sources/StreamChat/Controllers/PollController/PollController.swift
  Sources/StreamChat/Models/PollOption.swift
  Sources/StreamChat/Models/PollVote.swift
  Sources/StreamChat/Query/PollVoteListQuery.swift
  Sources/StreamChatUI/Appearance+Formatters/Appearance+Formatters.swift
  Sources/StreamChatUI/Appearance+Formatters/Calendar+StreamCalendar.swift
  Sources/StreamChatUI/Appearance+Formatters/ChannelListMessageTimestampFormatter.swift
  Sources/StreamChatUI/Appearance+Formatters/MessageTimestampFormatter.swift
  Sources/StreamChatUI/Appearance+Formatters/PollTimestampFormatter.swift
  Sources/StreamChatUI/Appearance+Images.swift
  Sources/StreamChatUI/ChatMessageList/Attachments/Poll/PollAttachmentOptionListView/PollAttachmentOptionListItemView.swift
  Sources/StreamChatUI/ChatMessageList/Attachments/Poll/PollResultsVC/PollResultsFooterButtonView.swift
  Sources/StreamChatUI/ChatMessageList/Attachments/Poll/PollResultsVC/PollResultsSectionHeaderOptionView.swift
  Sources/StreamChatUI/ChatMessageList/Attachments/Poll/PollResultsVC/PollResultsSectionHeaderView.swift
  Sources/StreamChatUI/ChatMessageList/Attachments/Poll/PollResultsVC/PollResultsTableHeaderView.swift
  Sources/StreamChatUI/ChatMessageList/Attachments/Poll/PollResultsVC/PollResultsVC.swift
  Sources/StreamChatUI/ChatMessageList/Attachments/Poll/PollResultsVC/PollResultsVoteItem/PollResultsVoteItemCell.swift
  Sources/StreamChatUI/ChatMessageList/Attachments/Poll/PollResultsVC/PollResultsVoteItem/PollResultsVoteItemView.swift
  Sources/StreamChatUI/ChatMessageList/Attachments/Poll/PollResultsVC/PollResultsVoteListVC/PollResultsVoteListVC.swift
  Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
  Sources/StreamChatUI/CommonViews/BaseViews.swift
  Sources/StreamChatUI/CommonViews/GroupedSectionListStyling.swift
  Sources/StreamChatUI/Components.swift
  Sources/StreamChatUI/Generated/L10n.swift
  Sources/StreamChatUI/Navigation/ChatMessageListRouter.swift
  Sources/StreamChatUI/Resources/en.lproj/Localizable.strings
  Sources/StreamChatUI/Utils/Extensions/Reusable+Extensions.swift
  StreamChat.xcodeproj/project.pbxproj
  Tests/StreamChatUITests/Mocks/Utils/Calendar_Mock.swift
  Tests/StreamChatUITests/SnapshotTests/ChatChannelList/ChatChannelListItemView_Tests.swift
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/Poll/PollAttachmentView_Tests.swift
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/Poll/PollMockFactory.swift
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/Poll/PollResultsVC_Tests.swift
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/Poll/PollResultsVoteListVC.swift
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/Poll/__Snapshots__/PollAttachmentView_Tests/test_appearance.default-light.png
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/Poll/__Snapshots__/PollAttachmentView_Tests/test_appearance.extraExtraExtraLarge-light.png
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/Poll/__Snapshots__/PollAttachmentView_Tests/test_appearance.rightToLeftLayout-default.png
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/Poll/__Snapshots__/PollAttachmentView_Tests/test_appearance.small-dark.png
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/Poll/__Snapshots__/PollAttachmentView_Tests/test_appearance_whenClosed.default-dark.png
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/Poll/__Snapshots__/PollAttachmentView_Tests/test_appearance_whenClosed.default-light.png
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/Poll/__Snapshots__/PollResultsVC_Tests/test_appearance.default-light.png
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/Poll/__Snapshots__/PollResultsVC_Tests/test_appearance.extraExtraExtraLarge-light.png
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/Poll/__Snapshots__/PollResultsVC_Tests/test_appearance.rightToLeftLayout-default.png
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/Poll/__Snapshots__/PollResultsVC_Tests/test_appearance.small-dark.png
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/Poll/__Snapshots__/PollResultsVC_Tests/test_appearance_whenClosed.default-dark.png
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/Poll/__Snapshots__/PollResultsVC_Tests/test_appearance_whenClosed.default-light.png
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/Poll/__Snapshots__/PollResultsVC_Tests/test_appearance_whenVotesMoreThanLimit.default-dark.png
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/Poll/__Snapshots__/PollResultsVC_Tests/test_appearance_whenVotesMoreThanLimit.default-light.png
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/Poll/__Snapshots__/PollResultsVoteListVC/test_appearance.default-light.png
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/Poll/__Snapshots__/PollResultsVoteListVC/test_appearance.extraExtraExtraLarge-light.png
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/Poll/__Snapshots__/PollResultsVoteListVC/test_appearance.rightToLeftLayout-default.png
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/Poll/__Snapshots__/PollResultsVoteListVC/test_appearance.small-dark.png
Labels: 🎨 SDK: StreamChatUI, ✅ Feature

#3401 [CI] Do not cache iOS Simulator Runtimes nightly
  .github/actions/setup-ios-runtime/action.yml
Labels: 🤖 CI/CD
