Repository GetStream/stream-chat-swift, pull requests merged in 2024-07, with the labels that each got.

#3275 Fix an edge case with a semicolon in user name
  CHANGELOG.md
  Sources/StreamChat/APIClient/RequestEncoder.swift
  Tests/StreamChatTests/APIClient/RequestEncoder_Tests.swift
Labels: 🌐 SDK: StreamChat (LLC)

#3280 [CI] Update frame rate diff value in xcmetrics report
  fastlane/Fastfile
Labels: 🤖 CI/CD

#3281 [CI] Do not fail jobs on unsuccessful removal of temp folders
  Scripts/install_ios_runtime.sh
Labels: 🤖 CI/CD

#3279 Always use in-memory database in tests
  StreamChat.xcodeproj/project.pbxproj
  TestTools/StreamChatTestTools/Extensions/FileManager+Extensions.swift
  TestTools/StreamChatTestTools/Extensions/Unique/URL+Unique.swift
  TestTools/StreamChatTestTools/SpyPattern/Spy/DatabaseContainer_Spy.swift
  Tests/StreamChatTests/APIClient/Endpoints/Payloads/ChannelListPayload_Tests.swift
  Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
  Tests/StreamChatTests/Controllers/MessageController/MessageController_Tests.swift
  Tests/StreamChatTests/Controllers/PollsControllers/PollController_Tests.swift
  Tests/StreamChatTests/Controllers/PollsControllers/PollVoteListController_Tests.swift
  Tests/StreamChatTests/Controllers/SearchControllers/UserController/UserController_Tests.swift
  Tests/StreamChatTests/Controllers/SearchControllers/UserListController/UserListController_Tests.swift
Labels: 🤖 CI/CD

#3282 [CI] Update the order of smoke checks
  .github/workflows/smoke-checks.yml
Labels: 🤖 CI/CD

#3284 [CI] Lint pod on release and nighty only
  .github/workflows/smoke-checks.yml
Labels: 🤖 CI/CD

#3288 Fix flakey tests due to using random reaction score and not waiting observers
  TestTools/StreamChatTestTools/TestData/DummyData/MessageReactionPayload.swift
  Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
  Tests/StreamChatTests/Database/DTOs/MessageDTO_Tests.swift
Labels: 🤖 CI/CD

#3290 Do not access DTOs from different threads in tests
  Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
  Tests/StreamChatTests/StreamChatFlakyTests.xctestplan
  Tests/StreamChatTests/StreamChatTestPlan.xctestplan
Labels: 🌐 SDK: StreamChat (LLC), 🤖 CI/CD

#3291 Use hash for differenceIdentifier after changing equatable
  Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
  Sources/StreamChatUI/ChatMessageList/ChatMessageListView+DiffKit.swift
Labels: 🐞 Bug, 🟢 QAed

#3286 [DemoApp] Allow to switch API keys
  DemoApp/Shared/DemoUsers.swift
  StreamChatUITestsApp/StreamChat/User.swift
  StreamChatUITestsAppUITests/Tests/Base TestCase/StreamTestCase.swift
  TestTools/StreamChatTestMockServer/Utilities/LaunchArgument.swift
Labels: 🪧 Demo App, 🤖 CI/CD

#3292 Typing indicator tests had timing issues
  Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
Labels: 🌐 SDK: StreamChat (LLC), 🤖 CI/CD

#3295 Fix animation when opening thread list
  Sources/StreamChatUI/ChatThreadList/ChatThreadListVC.swift
Labels: 🐞 Bug, 🎨 SDK: StreamChatUI, 🟢 QAed

#3297 Increase QoS for Throttler and Debouncer to utility
  CHANGELOG.md
  Sources/StreamChat/Utils/Debouncer.swift
  Sources/StreamChatUI/Utils/Throttler.swift
Labels: 🌐 SDK: StreamChat (LLC)

#3294 Add uniqueness constraint to ReactionListQueryDTO
  Sources/StreamChat/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
Labels: 🌐 SDK: StreamChat (LLC)

#3300 [CI] Revert jobs order
  .github/workflows/smoke-checks.yml
Labels: 🤖 CI/CD

#3308 [CI] XCMetrics report fix
  fastlane/Fastfile
Labels: 🤖 CI/CD

#3305 Reliable access to database models while observer is processing database changes
  CHANGELOG.md
  Sources/StreamChat/Controllers/ChannelListController/ChannelListController.swift
  Sources/StreamChat/Controllers/DatabaseObserver/BackgroundDatabaseObserver.swift
  Sources/StreamChat/Controllers/DatabaseObserver/BackgroundListDatabaseObserver.swift
  Sources/StreamChat/Controllers/SearchControllers/MessageSearchController/MessageSearchController.swift
  Sources/StreamChat/Controllers/ThreadListController/ThreadListController.swift
  Sources/StreamChat/StateLayer/DatabaseObserver/StateLayerDatabaseObserver.swift
  Sources/StreamChat/Utils/Database/DatabaseItemConverter.swift
  Tests/StreamChatTests/BackgroundListDatabaseObserver_Tests.swift
Labels: 🌐 SDK: StreamChat (LLC), ✅ Feature, 🟢 QAed

#3309 Xcode 16 fails to compile MessageDTO tests
  Tests/StreamChatTests/Database/DTOs/MessageDTO_Tests.swift
Labels: 🌐 SDK: StreamChat (LLC), 🤖 CI/CD

#3315 Revert waiting for delegates in unstable polls tests
  Tests/StreamChatTests/Controllers/PollsControllers/PollController_Tests.swift
  Tests/StreamChatTests/Controllers/PollsControllers/PollVoteListController_Tests.swift
Labels: 🤖 CI/CD

#3313 Fix Demo App Refresh Tokens + Connection Banner
  DemoApp/Screens/AppConfigViewController/AppConfigViewController.swift
  DemoApp/Shared/Token+Development.swift
  DemoApp/StreamChat/Components/Banner/BannerShowingConnectionDelegate.swift
  DemoApp/StreamChat/Components/DemoChatChannelListVC.swift
Labels: 🪧 Demo App

#3314 Add support for enabling message list view animations
  CHANGELOG.md
  DemoApp/Screens/AppConfigViewController/AppConfigViewController.swift
  Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageContentView.swift
  Sources/StreamChatUI/ChatMessageList/ChatMessageListView.swift
  Sources/StreamChatUI/Components.swift
Labels: ✅ Feature

#3303 Add timeout support when connecting user
  CHANGELOG.md
  DemoApp/Screens/AppConfigViewController/AppConfigViewController.swift
  DemoApp/Shared/StreamChatWrapper.swift
  DemoApp/StreamChat/Components/DemoChatChannelListErrorView.swift
  DemoApp/StreamChat/StreamChatWrapper+DemoApp.swift
  Sources/StreamChat/APIClient/RequestDecoder.swift
  Sources/StreamChat/ChatClient+Environment.swift
  Sources/StreamChat/ChatClient.swift
  Sources/StreamChat/Config/ChatClientConfig.swift
  Sources/StreamChat/Errors/ErrorPayload.swift
  Sources/StreamChat/Repositories/ConnectionRepository.swift
  Sources/StreamChat/Utils/StreamTimer/ScheduledStreamTimer.swift
  Sources/StreamChat/WebSocketClient/ConnectionStatus.swift
  Sources/StreamChat/WebSocketClient/WebSocketClient.swift
  Sources/StreamChat/Workers/Background/ConnectionRecoveryHandler.swift
  Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
  StreamChat.xcodeproj/project.pbxproj
  StreamChatUITestsAppUITests/Robots/UserRobot.swift
  TestTools/StreamChatTestTools/Mocks/StreamChat/ChatClient_Mock.swift
  TestTools/StreamChatTestTools/Mocks/StreamChat/WebSocketClient/WebSocketClient_Mock.swift
  TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/Background/ConnectionRecoveryHandler_Mock.swift
  Tests/StreamChatTests/Repositories/ConnectionRepository_Tests.swift
  Tests/StreamChatTests/WebSocketClient/ConnectionStatus_Tests.swift
  Tests/StreamChatTests/Workers/Background/ConnectionRecoveryHandler_Tests.swift
Labels: 🐞 Bug, 🌐 SDK: StreamChat (LLC), ✅ Feature, 🟢 QAed

#3320 Fix channel search view by refreshing the view state in both delegates
  Sources/StreamChatUI/ChatChannelList/Search/ChatChannelListSearchVC.swift
Labels: 🐞 Bug, 🎨 SDK: StreamChatUI, 🟢 QAed

#3321 Update CHANGELOG.md
  CHANGELOG.md
Labels: 📋 Docs

#3326 [CI] Automate merge to develop on release
  fastlane/Fastfile
Labels: 🤖 CI/CD

#3331 [CI] Show sdk size update on PR
  .github/workflows/performance-metrics.yml
  .github/workflows/sdk-size-metrics.yml
  .gitignore
  StreamChat.xcodeproj/project.pbxproj
  fastlane/Fastfile
Labels: 🤖 CI/CD

#3336 Unstable test_databaseContainer_removesAllData_whenShouldFlushOnStartIsTrue test
  Tests/StreamChatTests/Database/DatabaseContainer_Tests.swift
Labels: 🌐 SDK: StreamChat (LLC), 🤖 CI/CD

#3335 Improve performance of ChatChannel and ChatMessage equality
  CHANGELOG.md
  Sources/StreamChat/Models/Channel.swift
  Sources/StreamChat/Models/ChatMessage.swift
Labels: 🌐 SDK: StreamChat (LLC), ⚡ Performance

#3325 Improve performance of `ChatChannel` database model conversions ~7 times
  CHANGELOG.md
  Sources/StreamChat/Database/DTOs/ChannelDTO.swift
  Sources/StreamChat/Database/DTOs/MemberModelDTO.swift
  Sources/StreamChat/Database/DTOs/MessageDTO.swift
  Sources/StreamChat/Database/DTOs/UserDTO.swift
  Sources/StreamChat/Query/Sorting/ChannelMemberListSortingKey.swift
  Sources/StreamChat/Query/Sorting/UserListSortingKey.swift
  Tests/StreamChatTests/Database/DTOs/ChannelDTO_Tests.swift
Labels: 🌐 SDK: StreamChat (LLC), ⚡ Performance

#3337 Add environment value for injecting logging level for development
  DemoApp/StreamChat/StreamChatWrapper+DemoApp.swift
  DemoApp/StreamRuntimeCheck+StreamInternal.swift
Labels: 🪧 Demo App

#3316 Fix a rare issue with incorrect message order when sending messages offline
  CHANGELOG.md
  Sources/StreamChat/ChatClient.swift
  Sources/StreamChat/Database/DTOs/QueuedRequestDTO.swift
  Sources/StreamChat/Database/DatabaseSession.swift
  Sources/StreamChat/Repositories/MessageRepository.swift
  Sources/StreamChat/Repositories/OfflineRequestsRepository.swift
  Sources/StreamChat/Repositories/SyncRepository.swift
  Sources/StreamChat/StateLayer/Chat.swift
  Sources/StreamChat/Workers/Background/MessageSender.swift
  TestTools/StreamChatTestTools/Mocks/StreamChat/Database/DatabaseSession_Mock.swift
  TestTools/StreamChatTestTools/SpyPattern/Spy/APIClient_Spy.swift
  Tests/StreamChatTests/Repositories/OfflineRequestsRepository_Tests.swift
  Tests/StreamChatTests/Workers/Background/MessageSender_Tests.swift
Labels: 🐞 Bug, ❗️ High Priority, 🌐 SDK: StreamChat (LLC), 🟢 QAed

#3339 [CI] Comment SDK size on every commit
  .github/workflows/cron-checks.yml
  .github/workflows/sdk-performance-metrics.yml
  .github/workflows/sdk-size-metrics.yml
  .github/workflows/smoke-checks.yml
  fastlane/Fastfile
Labels: 🤖 CI/CD

#3341 [CI] Update SDK size rounding
  fastlane/Fastfile
Labels: 🤖 CI/CD

#3342 [CI] Also round size diff
  fastlane/Fastfile
Labels: 🤖 CI/CD

#3343 [CI] Fix Allure launch issue
  .github/workflows/cron-checks.yml
  .github/workflows/smoke-checks.yml
Labels: 🤖 CI/CD

#3340 Add Channel List `.hasUnread` filter
  CHANGELOG.md
  DemoApp/StreamChat/Components/DemoChatChannelListVC.swift
  Sources/StreamChat/Database/DTOs/ChannelDTO.swift
  Sources/StreamChat/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
  Sources/StreamChat/Query/ChannelListQuery.swift
  Sources/StreamChat/Query/Filter.swift
  Sources/StreamChat/Query/Sorting/ChannelListSortingKey.swift
  Tests/StreamChatTests/Controllers/ChannelListController/ChannelListController_Tests.swift
  Tests/StreamChatTests/Query/Sorting/ChannelListSortingKey_Tests.swift
Labels: 🐞 Bug, 🌐 SDK: StreamChat (LLC), ✅ Feature, 🟢 QAed

#3345 Fix message search not showing results for new search terms
  CHANGELOG.md
  Sources/StreamChatUI/ChatChannelList/Search/ChatChannelSearchVC.swift
  Sources/StreamChatUI/ChatChannelList/Search/ChatMessageSearchVC.swift
Labels: 🐞 Bug, ❗️ High Priority, 🎨 SDK: StreamChatUI, 🟢 QAed

#3346 [CI] Adjust sdk size report on release PRs
  .github/workflows/smoke-checks.yml
  fastlane/Fastfile
Labels: 🤖 CI/CD

#3347 [CI] Pass branch name to sdk size report
  .github/workflows/sdk-size-metrics.yml
  .github/workflows/smoke-checks.yml
Labels: 🤖 CI/CD

#3349 [CI] Correctly retrieve a git branch on CI
  .github/workflows/cron-checks.yml
  .github/workflows/publish-release.yml
  .github/workflows/sdk-performance-metrics.yml
  .github/workflows/sdk-size-metrics.yml
  .github/workflows/smoke-checks.yml
  .github/workflows/start-new-release.yml
  .github/workflows/testflight.yml
  fastlane/Allurefile
  fastlane/Fastfile
Labels: 🤖 CI/CD
