Repository GetStream/stream-chat-swift, pull requests merged in 2024-06, with the labels that each got.

#3233 Fix TestOps API request failure
  Gemfile.lock
  fastlane/Allurefile
  fastlane/Pluginfile
Labels: 🤖 CI/CD

#3240 [CI] Skip flaky unit test until further investigation
  Tests/StreamChatTests/APIClient/Endpoints/Payloads/ChannelListPayload_Tests.swift
Labels: 🤖 CI/CD

#3241 [CI] Resolve Allure Regression board issue
  Gemfile.lock
  fastlane/Pluginfile
Labels: 🤖 CI/CD

#3243 Fix Core Data model warnings in unit-tests
  Sources/StreamChat/Database/DatabaseContainer.swift
  TestTools/StreamChatTestTools/SpyPattern/Spy/DatabaseContainer_Spy.swift
Labels: 🌐 SDK: StreamChat (LLC), 🤖 CI/CD

#3239 Fix notifications muted state for the current user in channel members
  CHANGELOG.md
  Sources/StreamChat/Database/DTOs/ChannelDTO.swift
  Tests/StreamChatTests/Database/DTOs/ChannelDTO_Tests.swift
Labels: 🐞 Bug, 🌐 SDK: StreamChat (LLC)

#3244 Fix `channel.pinnedMessages` with missing messages
  CHANGELOG.md
  Sources/StreamChat/Database/DTOs/MessageDTO.swift
  Tests/StreamChatTests/Database/DTOs/MessageDTO_Tests.swift
Labels: 🐞 Bug, 🌐 SDK: StreamChat (LLC)

#3248 Add an option to switch API keys in the tests
  DemoApp/Shared/DemoUsers.swift
  StreamChatUITestsApp/StreamChat/User.swift
  StreamChatUITestsAppUITests/Tests/Base TestCase/StreamTestCase.swift
  StreamChatUITestsAppUITests/Tests/Performance/ChannelListScrollTime.swift
  TestTools/StreamChatTestMockServer/Utilities/LaunchArgument.swift
Labels: 🤖 CI/CD

#3246 [CI] Random test failure with test_loadReplies_whenIsFirstPage_shouldClearCurrentMessagesExcludingLocalOnly
  Sources/StreamChat/Database/DatabaseContainer.swift
  TestTools/StreamChatTestTools/SpyPattern/Spy/DatabaseContainer_Spy.swift
  Tests/StreamChatTests/Workers/MessageUpdater_Tests.swift
Labels: 🤖 CI/CD

#3234 Fix an issue with markdown ordered list processing
  CHANGELOG.md
  Sources/StreamChatUI/StreamSwiftyMarkdown/SwiftyMarkdown/SwiftyLineProcessor.swift
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/ChatMessage/ChatMessageContentView_Tests.swift
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/ChatMessage/__Snapshots__/ChatMessageContentView_Tests/test_appearance_whenMessageWithoutMarkdownOrderedListFromTheCurrentUserIsSent.default-dark.png
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/ChatMessage/__Snapshots__/ChatMessageContentView_Tests/test_appearance_whenMessageWithoutMarkdownOrderedListFromTheCurrentUserIsSent.default-light.png
Labels: 🐞 Bug, 🎨 SDK: StreamChatUI, 🟢 QAed

#3242 Fix inconsistent message text when editing the message again
  CHANGELOG.md
  Sources/StreamChat/Database/DTOs/MessageDTO.swift
  Sources/StreamChat/Workers/MessageUpdater.swift
  Tests/StreamChatTests/StateLayer/Chat_Tests.swift
Labels: 🟢 QAed

#3249 [CI] Resolve allure upload issue
  fastlane/Allurefile
Labels: 🤖 CI/CD

#3256 Update git username
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: 🤖 CI/CD

#3253 Add role argument to partial user updates
  CHANGELOG.md
  DemoApp/Screens/UserProfileViewController.swift
  Sources/StreamChat/APIClient/Endpoints/Payloads/UserPayloads.swift
  Sources/StreamChat/Controllers/CurrentUserController/CurrentUserController.swift
  Sources/StreamChat/StateLayer/ConnectedUser.swift
  Sources/StreamChat/Workers/CurrentUserUpdater.swift
  TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/CurrentUserUpdater_Mock.swift
  Tests/StreamChatTests/APIClient/Endpoints/Payloads/UserPayloads_Tests.swift
  Tests/StreamChatTests/APIClient/Endpoints/UserEndpoints_Tests.swift
  Tests/StreamChatTests/StateLayer/ConnectedUser_Tests.swift
  Tests/StreamChatTests/Workers/CurrentUserUpdater_Tests.swift
Labels: ✅ Feature, 🟢 QAed

#3257 [Demo app] Fallback to jpeg path extension if the downloaded file does not specify it
  DemoAppPush/NotificationService.swift
Labels: 🪧 Demo App

#3259 [CI] Make CI green again
  .github/workflows/cron-checks.yml
  .github/workflows/smoke-checks.yml
  .github/workflows/xcmetrics.yml
  Scripts/bootstrap.sh
  StreamChatUITestsAppUITests/Pages/MessageListPage.swift
  StreamChatUITestsAppUITests/Robots/UserRobot+Asserts.swift
  StreamChatUITestsAppUITests/Robots/UserRobot.swift
  StreamChatUITestsAppUITests/Tests/Attachments_Tests.swift
  StreamChatUITestsAppUITests/Tests/Base TestCase/StreamTestCase.swift
  StreamChatUITestsAppUITests/Tests/ChannelList_Tests.swift
  StreamChatUITestsAppUITests/Tests/Ephemeral_Messages_Tests.swift
  StreamChatUITestsAppUITests/Tests/Message Delivery Status/MessageDeliveryStatus+ChannelList_Tests.swift
  StreamChatUITestsAppUITests/Tests/Message Delivery Status/MessageDeliveryStatus_Tests.swift
  StreamChatUITestsAppUITests/Tests/MessageList_Tests.swift
  StreamChatUITestsAppUITests/Tests/PushNotification_Tests.swift
  StreamChatUITestsAppUITests/Tests/QuotedReply_Tests.swift
  StreamChatUITestsAppUITests/Tests/Reactions_Tests.swift
  StreamChatUITestsAppUITests/Tests/SlowMode_Tests.swift
  StreamChatUITestsAppUITests/Tests/UserDetails_Tests.swift
  TestTools/StreamChatTestMockServer/Utilities/LaunchArgument.swift
  fastlane/Fastfile
Labels: 🤖 CI/CD

#3252 [CI] Fix mock server sync issue
  .github/actions/python-cache/action.yml
Labels: 🤖 CI/CD

#3264 [CI] Update the custom e2e tests' retry strategy to cover all possible results
  StreamChatUITestsAppUITests/Robots/UserRobot+Asserts.swift
  fastlane/Fastfile
Labels: 🤖 CI/CD

#3260 Significantly improve performance of database observers
  CHANGELOG.md
  Sources/StreamChat/Config/StreamRuntimeCheck.swift
  Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
  Sources/StreamChat/Controllers/ChannelListController/ChannelListController.swift
  Sources/StreamChat/Controllers/ChannelWatcherListController/ChatChannelWatcherListController.swift
  Sources/StreamChat/Controllers/DatabaseObserver/BackgroundDatabaseObserver.swift
  Sources/StreamChat/Controllers/DatabaseObserver/BackgroundListDatabaseObserver.swift
  Sources/StreamChat/Controllers/DatabaseObserver/ListDatabaseObserver.swift
  Sources/StreamChat/Controllers/MemberListController/MemberListController.swift
  Sources/StreamChat/Controllers/MessageController/MessageController.swift
  Sources/StreamChat/Controllers/PollController/PollController.swift
  Sources/StreamChat/Controllers/PollController/PollVoteListController.swift
  Sources/StreamChat/Controllers/ReactionListController/ReactionListController.swift
  Sources/StreamChat/Controllers/SearchControllers/MessageSearchController/MessageSearchController.swift
  Sources/StreamChat/Controllers/ThreadListController/ThreadListController.swift
  Sources/StreamChat/Controllers/UserListController/UserListController.swift
  Sources/StreamChat/Database/DTOs/MessageReactionDTO.swift
  Sources/StreamChat/Database/DTOs/ThreadDTO.swift
  Sources/StreamChat/Models/MessageReaction.swift
  Sources/StreamChat/StateLayer/ChannelListState+Observer.swift
  Sources/StreamChat/StateLayer/ChatState+Observer.swift
  Sources/StreamChat/StateLayer/DatabaseObserver/StateLayerDatabaseObserver.swift
  Sources/StreamChat/StateLayer/MemberListState+Observer.swift
  Sources/StreamChat/StateLayer/MessageSearchState+Observer.swift
  Sources/StreamChat/StateLayer/MessageState+Observer.swift
  Sources/StreamChat/StateLayer/ReactionListState+Observer.swift
  Sources/StreamChat/StateLayer/UserListState+Observer.swift
  Sources/StreamChat/Utils/Database/DatabaseItemConverter.swift
  StreamChat.xcodeproj/project.pbxproj
  TestTools/StreamChatTestTools/Mocks/Models + Extensions/ChatMessageReaction_Mock.swift
  Tests/StreamChatTests/Controllers/ChannelWatcherListController/ChatChannelWatcherListController_Tests.swift
  Tests/StreamChatTests/Controllers/MemberListController/MemberListController_Tests.swift
  Tests/StreamChatTests/Controllers/MessageController/MessageController+Combine_Tests.swift
  Tests/StreamChatTests/Controllers/MessageController/MessageController+SwiftUI_Tests.swift
  Tests/StreamChatTests/Controllers/MessageController/MessageController_Tests.swift
  Tests/StreamChatTests/Controllers/ThreadListController/ChatThreadListController_Tests.swift
  Tests/StreamChatTests/Database/DTOs/MessageDTO_Tests.swift
  Tests/StreamChatTests/ListDatabaseObserverWrapper_Tests.swift
  Tests/StreamChatTests/Query/Sorting/ListDatabaseObserver+Sorting_Tests.swift
  Tests/StreamChatTests/StateLayer/StateLayerDatabaseObserver_Tests.swift
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/ChatMessage/ChatMessageLayoutOptionsResolver_Tests.swift
Labels: 🌐 SDK: StreamChat (LLC), ⚡ Performance, 🟢 QAed

#3268 [CI] Update frame rate row in xcmetrics report
  fastlane/Fastfile
Labels: 🤖 CI/CD

#3265 [CI] Update iOS runtimes' download
  .github/actions/setup-ios-runtime/action.yml
  .github/workflows/cron-checks.yml
  .github/workflows/smoke-checks.yml
  .gitignore
  Scripts/bootstrap.sh
  Scripts/install_ios_runtime.sh
  Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
  fastlane/.env
  fastlane/Fastfile
Labels: 🤖 CI/CD

#3223 Implement user block feature
  CHANGELOG.md
  DemoApp/Screens/AppConfigViewController/AppConfigViewController.swift
  DemoApp/StreamChat/Components/DemoChatChannelListRouter.swift
  Sources/StreamChat/APIClient/Endpoints/BlockedUserPayload.swift
  Sources/StreamChat/APIClient/Endpoints/EndpointPath+OfflineRequest.swift
  Sources/StreamChat/APIClient/Endpoints/EndpointPath.swift
  Sources/StreamChat/APIClient/Endpoints/ModerationEndpoints.swift
  Sources/StreamChat/APIClient/Endpoints/Payloads/ChannelCodingKeys.swift
  Sources/StreamChat/APIClient/Endpoints/Payloads/ChannelListPayload.swift
  Sources/StreamChat/APIClient/Endpoints/Payloads/CurrentUserPayloads.swift
  Sources/StreamChat/APIClient/Endpoints/Payloads/UserPayloads.swift
  Sources/StreamChat/Controllers/CurrentUserController/CurrentUserController.swift
  Sources/StreamChat/Controllers/UserController/UserController.swift
  Sources/StreamChat/Database/DTOs/ChannelDTO.swift
  Sources/StreamChat/Database/DTOs/CurrentUserDTO.swift
  Sources/StreamChat/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
  Sources/StreamChat/Models/BlockedUserDetails.swift
  Sources/StreamChat/Models/Channel.swift
  Sources/StreamChat/Models/CurrentUser.swift
  Sources/StreamChat/Models/UserInfo.swift
  Sources/StreamChat/Query/ChannelListQuery.swift
  Sources/StreamChat/StateLayer/ConnectedUser.swift
  Sources/StreamChat/WebSocketClient/EventMiddlewares/ChannelVisibilityEventMiddleware.swift
  Sources/StreamChat/WebSocketClient/WebSocketConnectPayload.swift
  Sources/StreamChat/Workers/CurrentUserUpdater.swift
  Sources/StreamChat/Workers/UserUpdater.swift
  Sources/StreamChatUI/Components.swift
  Sources/StreamChatUI/MessageActionsPopup/ChatMessageActionsVC.swift
  Sources/StreamChatUI/Resources/Assets.xcassets/Message Actions/icn_block_user.imageset/icn_block_user.pdf
  StreamChat.xcodeproj/project.pbxproj
  TestTools/StreamChatTestTools/Mocks/Models + Extensions/ChatChannelMember_Mock.swift
  TestTools/StreamChatTestTools/Mocks/Models + Extensions/CurrentChatUser_Mock.swift
  TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/UserUpdater_Mock.swift
  TestTools/StreamChatTestTools/TestData/DummyData/ChannelDetailPayload.swift
  TestTools/StreamChatTestTools/TestData/DummyData/XCTestCase+Dummy.swift
  Tests/StreamChatTests/APIClient/Endpoints/EndpointPath_Tests.swift
  Tests/StreamChatTests/APIClient/Endpoints/ModerationEndpoints_Tests.swift
  Tests/StreamChatTests/APIClient/Endpoints/Payloads/ChannelListPayload_Tests.swift
  Tests/StreamChatTests/APIClient/Endpoints/Payloads/IdentifiablePayload_Tests.swift
  Tests/StreamChatTests/Controllers/SearchControllers/UserController/UserController_Tests.swift
  Tests/StreamChatTests/Query/ChannelListFilterScope_Tests.swift
  Tests/StreamChatTests/StateLayer/ConnectedUser_Tests.swift
  Tests/StreamChatTests/WebSocketClient/EventMiddlewares/ChannelReadUpdaterMiddleware_Tests.swift
  Tests/StreamChatTests/Workers/UserUpdater_Tests.swift
  Tests/StreamChatUITests/SnapshotTests/MessageActionsPopup/ChatMessageActionsVC_Tests.swift
  docusaurus/docs/iOS/common-content/reference-docs/stream-chat-ui/components-properties.md
  docusaurus/docs/iOS/common-content/reference-docs/stream-chat-ui/components.md
  docusaurus/docs/iOS/common-content/reference-docs/stream-chat/api-client/endpoints/payloads/channel-coding-keys.md
  docusaurus/docs/iOS/common-content/reference-docs/stream-chat/api-client/endpoints/payloads/channel-config-properties.md
  docusaurus/docs/iOS/common-content/reference-docs/stream-chat/api-client/endpoints/payloads/channel-config.md
  docusaurus/docs/iOS/common-content/reference-docs/stream-chat/controllers/user-controller/chat-user-controller-properties.md
  docusaurus/docs/iOS/common-content/reference-docs/stream-chat/controllers/user-controller/chat-user-controller.md
  docusaurus/docs/iOS/common-content/reference-docs/stream-chat/models/current-chat-user-properties.md
  docusaurus/docs/iOS/common-content/reference-docs/stream-chat/models/current-chat-user.md
Labels: 🌐 SDK: StreamChat (LLC), 🎨 SDK: StreamChatUI, 🪧 Demo App, 🟢 QAed
