Repository GetStream/stream-chat-swift, pull requests merged in 2025-07, with the labels that each got.

#3716 [CI] Skip git hooks on merge and squash commits
  lefthook.yml
Labels: 🤖 CI/CD

#3723 [CI] Fix Sonar scanner on develop
  .github/workflows/sonar.yml
Labels: 🤖 CI/CD

#3725 [CI] Do not rebuild mint tools on every new macos build
  .github/actions/bootstrap/action.yml
Labels: 🤖 CI/CD

#3740 [CI] Implement public interface validation
  .github/workflows/smoke-checks.yml
  .gitignore
  Githubfile
  Scripts/bootstrap.sh
  fastlane/Fastfile
Labels: 🤖 CI/CD

#3743 [CI] Opt out from fastlane tracking
  fastlane/Fastfile
Labels: 🤖 CI/CD

#3748 Fix reaction picker position in RTL layout
  CHANGELOG.md
  Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatReactionsBubbleView.swift
  Sources/StreamChatUI/ChatMessageList/Reactions/ChatMessageReactionAuthorsVC/ChatMessageReactionAuthorViewCell.swift
  Sources/StreamChatUI/ChatMessageList/Reactions/ChatMessageReactionsBubbleTail.swift
  Sources/StreamChatUI/MessageActionsPopup/ChatMessagePopupVC.swift
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/Reactions/ChatMessageReactionAuthorsVC/__Snapshots__/ChatMessageReactionAuthorsVC_Tests/test_defaultAppearance.rightToLeftLayout-default.png
  Tests/StreamChatUITests/SnapshotTests/MessageActionsPopup/ChatMessagePopupVC_Tests.swift
  Tests/StreamChatUITests/SnapshotTests/MessageActionsPopup/__Snapshots__/ChatMessagePopupVC_Tests/test_appearanceCustomization_usingAppearance.rightToLeftLayout-default.png
  Tests/StreamChatUITests/SnapshotTests/MessageActionsPopup/__Snapshots__/ChatMessagePopupVC_Tests/test_defaultAppearance_when_largeLongMessage.rightToLeftLayout-default.png
Labels: 🐞 Bug, 🎨 SDK: StreamChatUI

#3744 Slide to cancel in audio recording did not cancel in RTL layout
  CHANGELOG.md
  Sources/StreamChatUI/Appearance+Images.swift
  Sources/StreamChatUI/VoiceRecording/Views/SlideToCancelView.swift
  Sources/StreamChatUI/VoiceRecording/VoiceRecordingVC.swift
  Tests/StreamChatUITests/SnapshotTests/VoiceRecording/Views/__Snapshots__/SlideToCancelView_Tests/test_appearance_snapshotsAreAsExpected.rightToLeftLayout-default-AlmostHidden.png
  Tests/StreamChatUITests/SnapshotTests/VoiceRecording/Views/__Snapshots__/SlideToCancelView_Tests/test_appearance_snapshotsAreAsExpected.rightToLeftLayout-default.png
Labels: 🐞 Bug, 🎨 SDK: StreamChatUI

#3746 Fix animating attachments when opening a sheet in the channel view
  CHANGELOG.md
  Sources/StreamChatUI/ChatMessageList/Attachments/File/ChatMessageFileAttachmentListView.swift
  Sources/StreamChatUI/ChatMessageList/Attachments/Gallery/ChatMessageGalleryView.swift
  Sources/StreamChatUI/ChatMessageList/Attachments/VoiceRecording/ChatMessageVoiceRecordingAttachmentListView.swift
Labels: 🐞 Bug, 🎨 SDK: StreamChatUI

#3749 Fix audio visualisation in RTL layout
  CHANGELOG.md
  Sources/StreamChatUI/VoiceRecording/Views/AudioVisualizationView.swift
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/Attachments/__Snapshots__/ChatMessageVoiceRecordingAttachmentListView_Tests/test_appearanceCustomization_usingSubclassing.rightToLeftLayout-default.png
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/Attachments/__Snapshots__/ChatMessageVoiceRecordingAttachmentListView_Tests/test_appearance_five_attachments.rightToLeftLayout-default.png
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/Attachments/__Snapshots__/ChatMessageVoiceRecordingAttachmentListView_Tests/test_appearance_one_attachment.rightToLeftLayout-default.png
  Tests/StreamChatUITests/SnapshotTests/ChatMessageList/Attachments/__Snapshots__/ChatMessageVoiceRecordingAttachmentListView_Tests/test_appearance_two_attachments.rightToLeftLayout-default.png
  Tests/StreamChatUITests/SnapshotTests/VoiceRecording/Views/__Snapshots__/AudioVisualizationView_Tests/test_appearance_nonSilence_snapshotsAreAsExpected.rightToLeftLayout-default.png
  Tests/StreamChatUITests/SnapshotTests/VoiceRecording/Views/__Snapshots__/AudioVisualizationView_Tests/test_appearance_silence_snapshotsAreAsExpected.rightToLeftLayout-default.png
  Tests/StreamChatUITests/SnapshotTests/VoiceRecording/Views/__Snapshots__/LiveRecordingView_Tests/test_appearance_isPaused_snapshotsAreAsExpected.rightToLeftLayout-default.png
  Tests/StreamChatUITests/SnapshotTests/VoiceRecording/Views/__Snapshots__/LiveRecordingView_Tests/test_appearance_isPlaying_snapshotsAreAsExpected.rightToLeftLayout-default.png
  Tests/StreamChatUITests/SnapshotTests/VoiceRecording/Views/__Snapshots__/LiveRecordingView_Tests/test_appearance_isRecording_snapshotsAreAsExpected.rightToLeftLayout-default.png
  Tests/StreamChatUITests/SnapshotTests/VoiceRecording/Views/__Snapshots__/WaveformView_Tests/test_appearance_isPlaying_snapshotsAreAsExpected.rightToLeftLayout-default.png
  Tests/StreamChatUITests/SnapshotTests/VoiceRecording/Views/__Snapshots__/WaveformView_Tests/test_appearance_isRecording_snapshotsAreAsExpected.rightToLeftLayout-default.png
Labels: 🐞 Bug, 🎨 SDK: StreamChatUI

#3757 [CI] Fix swiftformat exclude paths
  lefthook.yml
Labels: 🤖 CI/CD
