Repository GetStream/stream-chat-swift, pull requests merged in 2025-02, with the labels that each got.

#3579 [CI] Update mock server sync script
  .github/workflows/smoke-checks-llc.yml
  .github/workflows/smoke-checks.yml
  .github/workflows/sync-mock-server.yml
  Gemfile
  Gemfile.lock
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/http_add_member.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/http_attachment.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/http_channel_creation.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/http_channel_removal.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/http_channels.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/http_events.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/http_giphy_link.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/http_message.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/http_message_ephemeral.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/http_reaction.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/http_truncate.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/http_unsplash_link.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/http_youtube_link.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/ws_events.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/ws_events_channel.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/ws_events_member.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/ws_health_check.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/ws_message.json
  TestTools/StreamChatTestMockServer/Fixtures/JSONs/ws_reaction.json
  fastlane/Fastfile
  fastlane/sync_mock_server.py
  fastlane/sync_mock_server.rb
  requirements.txt
Labels: 🤖 CI/CD

#3584 [CI] Run sonar on push
  .github/actions/python-cache/action.yml
  .github/workflows/smoke-checks-llc.yml
  .github/workflows/smoke-checks.yml
  .github/workflows/sonar.yml
  fastlane/Fastfile
  fastlane/Sonarfile
  requirements.txt
Labels: 🤖 CI/CD

#3587 [CI] Remove unused sonar arguments
  fastlane/Sonarfile
Labels: 🤖 CI/CD

#3586 [Enhancement]Allow passing options on AVURLAsset init
  CHANGELOG.md
  Sources/StreamChat/Audio/AudioPlayer/AudioPlaying.swift
Labels: ✨ Enhancement

#3574 Fix updating channel's preview message when coming back to online
  CHANGELOG.md
  Sources/StreamChat/Utils/Database/NSManagedObject+Extensions.swift
  Tests/StreamChatTests/Database/FetchCache_Tests.swift
Labels: 🐞 Bug, 🌐 SDK: StreamChat (LLC), 🟢 QAed

#3589 [CI] Snapshots recording improvement
  .github/workflows/record-snapshots.yml
  .github/workflows/smoke-checks.yml
  fastlane/Fastfile
Labels: 🤖 CI/CD

#3594 [CI] Optimize snapshots recording job
  .github/workflows/record-snapshots.yml
  .github/workflows/smoke-checks.yml
  fastlane/Fastfile
Labels: 🤖 CI/CD

#3591 Remove SwiftyMarkdown
  .swiftlint.yml
  Makefile
  Scripts/run-linter.sh
  Scripts/updateDependency.sh
  Sources/StreamChatUI/StreamSwiftyMarkdown/SwiftyMarkdown/CharacterRule.swift
  Sources/StreamChatUI/StreamSwiftyMarkdown/SwiftyMarkdown/PerfomanceLog.swift
  Sources/StreamChatUI/StreamSwiftyMarkdown/SwiftyMarkdown/String+SwiftyMarkdown.swift
  Sources/StreamChatUI/StreamSwiftyMarkdown/SwiftyMarkdown/SwiftyLineProcessor.swift
  Sources/StreamChatUI/StreamSwiftyMarkdown/SwiftyMarkdown/SwiftyMarkdown+iOS.swift
  Sources/StreamChatUI/StreamSwiftyMarkdown/SwiftyMarkdown/SwiftyMarkdown+macOS.swift
  Sources/StreamChatUI/StreamSwiftyMarkdown/SwiftyMarkdown/SwiftyMarkdown.swift
  Sources/StreamChatUI/StreamSwiftyMarkdown/SwiftyMarkdown/SwiftyScanner.swift
  Sources/StreamChatUI/StreamSwiftyMarkdown/SwiftyMarkdown/SwiftyTokeniser.swift
  Sources/StreamChatUI/StreamSwiftyMarkdown/SwiftyMarkdown/Token.swift
  Sources/StreamChatUI/Utils/Extensions/String+Extensions.swift
  StreamChat.xcodeproj/project.pbxproj
  hooks/pre-commit.sh
Labels: 🎨 SDK: StreamChatUI

#3599 [CI] Bump Allure version
  Githubfile
Labels: 🤖 CI/CD

#3602 Fix message transformer not being applied when editing a message
  CHANGELOG.md
  Sources/StreamChat/Controllers/MessageController/MessageController.swift
  Tests/StreamChatTests/Controllers/MessageController/MessageController_Tests.swift
Labels: 🐞 Bug
